### ISSUE TITLE
API Implementation Tracker [your wanted APIs go here]

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-node#1338]
This is a list of APIs that are known to be wanted, but yet to be implemented into gcloud-node. We will update this issue to give visibility into the prioritization and progress of each.

## To Be Prioritized
- App Engine Admin API
- [App Engine Task Queue](https://cloud.google.com/appengine/docs/python/taskqueue/rest)
- Cloud CDN
- Cloud Endpoints
- Cloud Functions
- Cloud SQL
- [Compute Engine Beta API](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1478)
- [Compute Engine Metadata API](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/917)
- [Container Engine](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2578)
- [Apiary Photos API](https://github.com/googleapis/google-api-nodejs-client/issues/1695)

## New Requests

If you'd like us to support an API that is not on this list, feel free to add your request in a comment. If a comment has already been made with your request, +1 it.

**Comment by karthiksekarnz** [comment]
Guys, I would really like to see a cloud endpoints and CDN.  I might deploy a loopback api gateway with cloud datastore in the meantime.

**Comment by jasonpolites** [comment]
Would it make sense to keep the discrete source issues open so users can still comment/upvote a specific issue?  Might help determine a customer-driven priority.

**Comment by stephenplusplus** [comment]
Having multiple issues led to repeated issues and lots of noise. I'd like to see how far we can stretch making this one issue work. Anyone can feel free to vote for their wanted APIs here / +1 the last person's comment that requested something. Ultimately, @jgeewax will officiate the ordering of the implementations.

**Comment by jasonpolites** [comment]
Upvote this comment if you want Cloud Functions support!  ;)

**Comment by micaww** [comment]
Search & Images! I have to use outsource to Python modules to accomplish some simple tasks from my Node.js default module

**Comment by Ryboii** [comment]
Images API

**Comment by kriptontr** [comment]
Please implement get_serving_url() in ptyhon api to node like as seen here 
https://cloud.google.com/appengine/docs/standard/python/refdocs/google.appengine.api.images#Image_get_serving_url

**Comment by kriptontr** [comment]
I wish i could take advantage of magic image urls in node api like referenced as there
https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.images#Image_get_serving_url

**Comment by tyrw** [comment]
Sequelize CLI

**Comment by prescottprue** [comment]
Cloud Functions Admin API (list/create/delete)

**Comment by Philmod** [comment]
Google Cloud Container Builder (GCB)

**Comment by JustinBeckwith** [comment]
@theacodes  @danoscarmike guessing this is not how we're tracking this stuff now :)  Should I just close this out?

**Comment by stephenplusplus** [comment]
These are user requests, so having a channel for this type of feedback, whether here or somewhere else, is valuable.

**Comment by govindrai** [comment]
@stephenplusplus any status on these? Where is the new place you guys are tracking this? Cloud SQL and App Engine APIs would be absolutely exceptional.

**Comment by stephenplusplus** [comment]
Recommendations AI (via @klaussilveira in #2960)

**Comment by JustinBeckwith** [comment]
Hey folks following up here - there are a variety of new APIs available now:
- https://github.com/googleapis/nodejs-functions
- https://github.com/googleapis/nodejs-cloudbuild

The complete list for those looking, is in the README here:
https://github.com/googleapis/google-cloud-node

**Comment by Mistic92** [comment]
Hi, do you have any ETA for Recommendations AI?

**Comment by bcoe** [comment]
@Mistic92 no concrete time, but I believe it is on our list of APIs to generate soon.

**Comment by bcoe** [comment]
This thread is a bit stale (and hasn't had many updates recently) so closing out.

Since 2016, we have introduced 100s of client libraries, and continuing to provide client libraries for GA GCP products continues to be a top priority for the team.
