### ISSUE TITLE
Link out to each github repo hosting the specific client lib

### ISSUE THREAD

**Issue by cobookman** [googleapis/google-cloud-node#2818]
This repo when mentioning "Spanner Nodejs" should have a link to where the code lives as well as a link back to the google cloud webpage.

**Comment by stephenplusplus** [comment]
Can you show an example of where you would like a link? This is pretty much a dead repo, where the README should be pointing to the new homes of the client libraries.

**Comment by cobookman** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-node#cloud-spanner-ga

**Comment by stephenplusplus** [comment]
Makes sense! I'm marking as `help wanted` in case anyone wants to contribute :)

**Comment by JustinBeckwith** [comment]
@bcoe thinking out loud - it would be really fun to automate this:
- Create a webhook for googleapis/sloth
- Set up a cloud function to handle the hook in the yoshi-team project
- When `repos.json` changes, run a small tool that generates this readme (code can be in this repo)
- Have the tool submit a PR to this repo to make the update

Would be good to chat with @busunkim96 who's making a proposal for a generic metadata file that should live in the root of all repos, though we can depend on `.cloud-repo-tools.json` for now.
