### ISSUE TITLE
I really should stop publishing empty npm packages

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2824]
So, I keep publishing empty npm modules.  Accidentally of course.  Turns out that `npm prepare` failing to run *doesn't* actually cause a non-0 exit code.  See this for example:
https://circleci.com/gh/googleapis/nodejs-common/2847

```sh
#!/bin/bash -eo pipefail
npm publish
npm WARN lifecycle @google-cloud/common@0.19.0~prepare: cannot run in wd %s %s (wd=%s) @google-cloud/common@0.19.0 npm run compile .
+ @google-cloud/common@0.19.0
```

What you see right there is `npm prepare` failing, yet still letting `npm publish` continue with a 0 exit code ....  The result is the publishing of an empty npm module with no `build` directory.  

Do folks have any thoughts on how we could test this before publishing empty modules? 

@ofrobots @alexander-fenster @kinwa91 @GoogleCloudPlatform/node-team

**Comment by jinwoo** [comment]
If it's true that a failing `npm prepare` doesn't cause a non-zero exit code, maybe we should file a bug against `npm`?

**Comment by JustinBeckwith** [comment]
This bit us again in https://github.com/googleapis/nodejs-storage/issues/741.

**Comment by JustinBeckwith** [comment]
I think we're good now :)
