### ISSUE TITLE
What is the SLO for releasing?

### ISSUE THREAD

**Issue by ofrobots** [googleapis/google-cloud-node#2828]
Context: https://github.com/googleapis/nodejs-common-grpc/issues/74

Three months of changes have piled up. What should be our objective on a release cadence? How can we simplify / automate the release process?

IMO it is not enough to track issue resolution SLO when we are not tracking a release SLO. A P1 issue isn't really fixed if we have landed the fix but haven't released it.

**Comment by ofrobots** [comment]
I am asking for node.js specifically.

IMO we should be idiomatic for each language even if it means we have
different answers got each language.

**Comment by JustinBeckwith** [comment]
We now have `release-please` running on all nodejs repositories, which adds a 7 day SLO for all PRs.  So ... 7 days, and now mostly easy with tooling :) Closing this one out unless y'all think there's more to do here!
