### ISSUE TITLE
File upload:api error not found

### ISSUE THREAD

**Issue by lonelywoman** [googleapis/google-cloud-node#2852]
```
  -ApiError: Not Found
    at Object.parseHttpRespBody (/etc/son/server/node_modules/@google-cloud/common/src/util.js:193:30)
    at Object.handleResp (/etc/son/server/node_modules/@google-cloud/common/src/util.js:131:18)
    at /etc/son/server/node_modules/@google-cloud/common/src/util.js:496:12
    at Request.onResponse [as _callback] (/etc/son/server/node_modules/retry-request/index.js:198:7)
    at Request.self.callback (/etc/son/server/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/etc/son/server/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/etc/son/server/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
  code: 404,
  errors:
   [ { domain: 'global', reason: 'notFound', message: 'Not Found' } ],
  response: undefined,
  message: 'Not Found' } 
```

I get this error,when i want to file upload.
Nodejs:8x
Debian 8
I  know google-cloud deprecated and i read same issue.

**Comment by lonelywoman** [comment]
And npm 6.3.0

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share:
- which npm module are you using?
- a small code sample that demonstrates the problem

**Comment by lonelywoman** [comment]
hi again sory @JustinBeckwith i use only google cloud module.
```
var storage = require('@google-cloud/storage');
var gcs = storage({

  projectId: 'myid',
  keyFilename: 'mykeyfile.json'
});
var bucket = gcs.bucket('mybucket');
app.post('/upload',function(req,res){
  bucket.upload('sefer.jpg', function(err, file) {
    if(err){console.log(err)};
    if (!err) {
        console.log("its oke")
      }
  });
})
```

**Comment by lonelywoman** [comment]
no @stephenplusplus my bucket name is true. i create new bucket?

**Comment by stephenplusplus** [comment]
Does the bucket exist before the call to `bucket.upload`?

**Comment by lonelywoman** [comment]
y exist

**Comment by lonelywoman** [comment]
my bucket name was false:D i add true bucket name.but new error 

```
domain: 'global',
       reason: 'forbidden',
       message: 'starting-account-67n988tuygj7@sonproje-1533259273248.iam.gserviceaccount.com does not have storage.objects.create access to yiginlabilgi/sefer.jpg.'
```

**Comment by stephenplusplus** [comment]
This is related to the permissions of the account you're authorizing with here:

```js
var gcs = storage({
  projectId: 'myid',
  keyFilename: 'mykeyfile.json'
});
```

The project ID that is passed in here should match the project that owns the bucket.

Are you using the Requester Pays feature (more info here: https://cloud.google.com/storage/docs/requester-pays)?

**Comment by lonelywoman** [comment]
i use requester pay.and my proje  id is myproje-12121232..... or 12121232?

**Comment by stephenplusplus** [comment]
If you're trying to access a different bucket, you'll have to provide the `userProject` setting on the Bucket instance:

```js
const bucketFromAnotherProject = gcs.bucket('bucket-name', {
  userProject: 'your-own-project-id'
})
```

All requests that you make from the `bucketFromAnotherProject` object should route the billing to the `your-own-project-id` account.

**Comment by lonelywoman** [comment]
i have only one bucket and one project.

**Comment by stephenplusplus** [comment]
Requester Pays is a feature that lets you send requests to another project owner's bucket, but paying for that access from your project.

This error message: "Bucket is requester pays bucket but no user project provided." means that the feature is enabled on the bucket you're trying to access. If you are the owner of the bucket, and you mistakenly enabled requester pays, you can disable it: https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/Bucket#disableRequesterPays

To clear up some preliminary usage requirements:

- The project ID you should provide to the constructor is the customized name you chose when you created the project, or when you activated an API that required you to create a project ID.
- The keyFilename should be the path to a service account JSON file created for that project.

**Comment by lonelywoman** [comment]
i disable it;but now:
`starting-account-67n988tuygj7@sonproje-1533259273248.iam.gserviceaccount.com does not have storage.objects.create access to yiginlabilgi/sefer.jpg.' `

**Comment by lonelywoman** [comment]
i must define myproject to bucket?

**Comment by lonelywoman** [comment]
again same error:D

**Comment by stephenplusplus** [comment]
Sorry for the delay-- have you made any progress?
