### ISSUE TITLE
Come up a mechanism to produce 'jsdoc' documentation for TypeScript repos

### ISSUE THREAD

**Issue by ofrobots** [googleapis/google-cloud-node#2853]
Forked from https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/283#issuecomment-413062314

We need a consistent mechanism across all the libraries to be able to generate TypeScript docs.

**Comment by JustinBeckwith** [comment]
I think we now have this with compodoc.

**Comment by maxArturo** [comment]
Hi @JustinBeckwith any idea how users could get to these docs? I came from https://github.com/googleapis/cloud-trace-nodejs/issues/523 ; was looking around for config options in the cloud-trace-nodejs
repo and they weren't documented there. Had to dig into the actual plugin file to find what I needed 😞 .
