### ISSUE TITLE
Investigate remaining Kokoro failures

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2864]
- [x] https://github.com/googleapis/nodejs-translate/pull/127 - translate requires an `API_KEY` in it's env var config. 
- [x] https://github.com/googleapis/nodejs-os-login/pull/76 - all of the kokoro tests seemed to hang
- [x] https://github.com/googleapis/nodejs-dns/pull/110 - system tests are failing.  I think there's an env var in circleCI we need to bring over. 
- [x] https://github.com/googleapis/nodejs-dlp/pull/144 - not sure why, the samples tests are failing
- [ ] https://github.com/googleapis/nodejs-storage/pull/406 - the system tests are failing here
- [x] https://github.com/googleapis/nodejs-dialogflow/pull/171 - no backend config
- [ ] https://github.com/googleapis/nodejs-logging/pull/225 - needs an updated synth file

**Comment by carnesen** [comment]
I was curious about those pesky kokoro ❌'s showing up on PRs. Is that purely Google-internal thing, or can I read about it somewhere? Googling "Google kokoro", it seems to be a Jenkins replacement, but that's all I could determine.

**Comment by JustinBeckwith** [comment]
Calling this fixed for now 👍
