### ISSUE TITLE
Update all samples to use async/await

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2869]
Most of our samples are using promises for async programming, which is great.  Now that Node 8 is the latest LTS, and 10 is about to go out - we should start converting all the samples to async/await.  Lets use this as a high level tracking bug.  

- [x] [googleapis/google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client)
- [x] [googleapis/google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs)
- [x] [googleapis/nodejs-spanner](https://github.com/googleapis/nodejs-spanner)
- [x] [googleapis/nodejs-firestore](https://github.com/googleapis/nodejs-firestore)
- [x] [googleapis/nodejs-compute](https://github.com/googleapis/nodejs-compute)
- [ ] [googleapis/nodejs-bigtable](https://github.com/googleapis/nodejs-bigtable)
- [x] [googleapis/nodejs-common-grpc](https://github.com/googleapis/nodejs-common-grpc)
- [x] [googleapis/nodejs-common](https://github.com/googleapis/nodejs-common)
- [x] [googleapis/nodejs-kms](https://github.com/googleapis/nodejs-kms)
- [x] [googleapis/nodejs-iot](https://github.com/googleapis/nodejs-iot)
- [x] [googleapis/nodejs-error-reporting](https://github.com/googleapis/nodejs-error-reporting)
- [x] [googleapis/nodejs-redis](https://github.com/googleapis/nodejs-redis)
- [x] [googleapis/nodejs-vision](https://github.com/googleapis/nodejs-vision)
- [x] [googleapis/gax-nodejs](https://github.com/googleapis/gax-nodejs)
- [x] [googleapis/nodejs-translate](https://github.com/googleapis/nodejs-translate)
- [x] [googleapis/nodejs-text-to-speech](https://github.com/googleapis/nodejs-text-to-speech)
- [x] [googleapis/nodejs-os-login](https://github.com/googleapis/nodejs-os-login)
- [x] [googleapis/nodejs-dataproc](https://github.com/googleapis/nodejs-dataproc)
- [x] [googleapis/nodejs-bigquery-data-transfer](https://github.com/googleapis/nodejs-bigquery-data-transfer)
- [x] [googleapis/nodejs-video-intelligence](https://github.com/googleapis/nodejs-video-intelligence)
- [x] [googleapis/nodejs-speech](https://github.com/googleapis/nodejs-speech)
- [x] [googleapis/nodejs-resource](https://github.com/googleapis/nodejs-resource)
- [x] [googleapis/nodejs-pubsub](https://github.com/googleapis/nodejs-pubsub)
- [x] [googleapis/nodejs-monitoring](https://github.com/googleapis/nodejs-monitoring)
- [x] [googleapis/nodejs-logging-winston](https://github.com/googleapis/nodejs-logging-winston)
- [x] [googleapis/nodejs-logging](https://github.com/googleapis/nodejs-logging)
- [x] [googleapis/nodejs-logging-bunyan](https://github.com/googleapis/nodejs-logging-bunyan)
- [x] [googleapis/nodejs-language](https://github.com/googleapis/nodejs-language)
- [x] [googleapis/nodejs-dns](https://github.com/googleapis/nodejs-dns)
- [x] [googleapis/nodejs-dlp](https://github.com/googleapis/nodejs-dlp)
- [ ] [googleapis/nodejs-datastore](https://github.com/googleapis/nodejs-datastore)
- [x] [googleapis/nodejs-bigquery](https://github.com/googleapis/nodejs-bigquery)
- [x] [googleapis/nodejs-cloud-container](https://github.com/googleapis/nodejs-cloud-container)
- [x] [googleapis/nodejs-proto-files](https://github.com/googleapis/nodejs-proto-files)
- [x] [googleapis/nodejs-storage](https://github.com/googleapis/nodejs-storage)
- [x] [googleapis/nodejs-automl](https://github.com/googleapis/nodejs-automl)
- [x] [googleapis/nodejs-promisify](https://github.com/googleapis/nodejs-promisify)
- [x] [googleapis/nodejs-projectify](https://github.com/googleapis/nodejs-projectify)
- [x] [googleapis/nodejs-paginator](https://github.com/googleapis/nodejs-paginator)
- [x] [googleapis/google-p12-pem](https://github.com/googleapis/google-p12-pem)
- [x] [googleapis/node-gtoken](https://github.com/googleapis/node-gtoken)
- [x] [googleapis/nodejs-tasks](https://github.com/googleapis/nodejs-tasks)
- [x] [googleapis/google-cloud-node](https://github.com/googleapis/google-cloud-node)
- [x] [googleapis/cloud-trace-nodejs](https://github.com/googleapis/cloud-trace-nodejs)
- [x] [googleapis/cloud-debug-nodejs](https://github.com/googleapis/cloud-debug-nodejs)
- [x] [googleapis/github-repo-automation](https://github.com/googleapis/github-repo-automation)
- [x] [GoogleCloudPlatform/cloud-profiler-nodejs](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs)
- [x] [googleapis/gcs-resumable-upload](https://github.com/googleapis/gcs-resumable-upload)
- [x] [googleapis/gcp-metadata](https://github.com/googleapis/gcp-metadata)
- [x] [googleapis/google-cloud-kvstore](https://github.com/googleapis/google-cloud-kvstore)
- [x] [googleapis/gce-images](https://github.com/googleapis/gce-images)
- [x] [googleapis/nodejs-googleapis-common](https://github.com/googleapis/nodejs-googleapis-common)
- [x] [googleapis/nodejs-asset](https://github.com/googleapis/nodejs-asset)
- [x] [googleapis/sloth](https://github.com/googleapis/sloth)
- [ ] [googleapis/nodejs-dialogflow](https://github.com/googleapis/nodejs-dialogflow)

@sduskis this is something that we should have our new friends help with :)

To call out the specific work:
- All samples should use `async` or `await` instead of promises or callbacks
- We can remove all of the catch clauses that just print the output to console.error (a throw will do that anyway)

**Comment by JustinBeckwith** [comment]
cc @ofrobots

**Comment by sduskis** [comment]
@JustinBeckwith did you mean to close this?  There's still plenty of work to be done.

**Comment by vijay-qlogic** [comment]
@JustinBeckwith For [nodejs-iot](https://github.com/googleapis/nodejs-iot) No tests specified to run. Any changes required here?
