### ISSUE TITLE
Session not found error still happens

### ISSUE THREAD

**Issue by voltrue2** [googleapis/google-cloud-node#2874]
#### Environment details

  - OS: CentOS 
  - Node.js version: 8.x
  - npm version: 6.x
  - google-cloud-node version: 1.4.1

#### Steps to Reproduce

1. Keep connections open for more then an hour.

Hello 

We are still seeing this exact error. It seems to happen every one hour so it really fits the definition given here.
We create each connection with keepAlive option, but it does not seem to be working.
The version of the library we are using is 1.4.1
We are updating it to 2.0.0 in the near future but any help with is error will be appreciated.

Issue related: #2061 

Thanks

**Comment by JustinBeckwith** [comment]
This issue was moved to googleapis/nodejs-spanner#387
