### ISSUE TITLE
Remove usage of promisifyAll

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2887]
So this is more of a discussion topic than a task, but here we go.  In a lot of our libraries, we have a callback-first mentality.  We assume callback, and then brute force `promisifyAll` on many classes.  I'd like to flip this bit.  We should assume async first, then provide callbackification as needed. Thoughts on the subject appreciated!

**Comment by callmehiphop** [comment]
Would this require a signature change for the callback version though?

**Comment by JustinBeckwith** [comment]
Nope!  This would be exactly the same as `promisifyAll`, but different, but the same.

**Comment by callmehiphop** [comment]
Haha, ok. So as far as the scope of this issue is concerned, promises would still return Arrays and we'd more or less just spread that to the callback. SGTM!

**Comment by danielbankhead** [comment]
Handling this on a case-by-case basis.
