### ISSUE TITLE
Kokoro Status Not Updated in Pull Request

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/google-cloud-node#2889]
I have noticed that tests would complete successfully (as can be seen by looking at the Kokoro logs).  However, the status on a PR remains listed as "running" which prevents one from merging the PR and requires a force merge.

This was seen in:
* https://github.com/googleapis/nodejs-logging-bunyan/pull/216
* https://github.com/googleapis/nodejs-logging-bunyan/pull/217

**Comment by DominicKramer** [comment]
This is blocking the master branch from being green on [logging bunyan](https://github.com/googleapis/nodejs-logging-bunyan/commits/master) that is blocking our ability to make a new release of the library that needs to go out.

**Comment by ofrobots** [comment]
@JustinBeckwith this is blocking our ability to release. Can this be looked at? I don't have permissions to modify labels, but I believe this is a P0 or P1.

**Comment by JustinBeckwith** [comment]
@kinwa91 - can you please take a look?

**Comment by DominicKramer** [comment]
I've identified an issue in logging bunyan [(PR 232)](https://github.com/googleapis/nodejs-logging-bunyan/pull/232) that should fix the issue.  Before anyone else investigates, we should see if it addresses the issue.

**Comment by DominicKramer** [comment]
This has been resolved with logging-bunyan [(PR 232)](https://github.com/googleapis/nodejs-logging-bunyan/pull/232), and the samples tests on master are now green after the PR landed.
