### ISSUE TITLE
improve promise documentation

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-node#2894]
When we originally wrote a lot of the examples/samples for promise usage we still supported versions of Node that did not have destructuring support. Now we don't! It would be great if we could update the samples/examples to remove any snippets that access items via indices.

We also might want to consider using async/await since Node@6 is approaching its end of life (April 2019).

Before

```js
table.read(query)
  .then(function(data) {
     const rows = data[0];
  });
```

After

```js
const [rows] = await table.read(query);
```

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
