### ISSUE TITLE
tracking issue: Publish google api node modules through new publish tool

### ISSUE THREAD

**Issue by soldair** [googleapis/google-cloud-node#2897]
/cc @JustinBeckwith 
the publish service is available and i believe all of the blockers have been resolved.
Time to reconfigure publish of google node modules though wombat dressing room.

**Comment by JustinBeckwith** [comment]
@kinwa91 just checking in - what's the state of this one?

**Comment by soldair** [comment]
\o just checking up on this.

**Comment by JustinBeckwith** [comment]
Ready to call this one done 👍
