### ISSUE TITLE
Support OAuth 2.0 authentication

### ISSUE THREAD

**Issue by thecodejunkie** [googleapis/google-cloud-node#2898]
Since OAuth 2.0 is a supported authentication methods for Google APIs, it would be nice if these set of APIs supported it. You can already do it using `google-auth-library` together with the `googleapis`. I am currently writing an application (that supports multi-tenancy) which performs operations on behalf of the users, so the OAuth flow is the natural choice, since handling API keys or Service Accounts is a much less smooth approach.

**Comment by JustinBeckwith** [comment]
Good call.  This shouldn't be terribly hard since we're using `google-auth-library` under the hood for auth, which has all of the corresponding OAuth2 junk.  @googleapis/yoshi do any of the other cloud libraries support OAuth2 workflows out of the box?

**Comment by jskeet** [comment]
The .NET library has support for a few workflows out of the box. @chrisdunelm knows more than I do; docs are at https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth. We recently released an ASP.NET Core MVC package as well, which isn't documented there yet.

**Comment by thecodejunkie** [comment]
@jskeet fancy meeting you here 😄

**Comment by theacodes** [comment]
Python's former library did have flows for oauth2 stuff, but the new
google-auth library does not have these built-in. It has core support for
*using* OAuth 2.0 credentials, but *obtaining* them is separate - you use
the google-auth-oauthlib package for that.

**Comment by LindaLawton** [comment]
I just tried to use the new Google analytics data api with the node js library.

It worked fine when feeding it a service account credential file, however when feeding it an Oauth2 credential file it gives the following error

```
(node:14561) UnhandledPromiseRejectionWarning: Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/home/linda/WebstormProjects/google_nodejs_samples/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/jwtclient.js:195:19)
    at GoogleAuth._cacheClientFromJSON (/home/linda/WebstormProjects/google_nodejs_samples/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:301:16)
    at ReadStream.<anonymous> (/home/linda/WebstormProjects/google_nodejs_samples/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:335:36)
    at ReadStream.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

As mentioned perilously in this thread the above works just fine with the .net cloud library.     I find it strange that this library would only support service account authentication.

**Comment by danoscarmike** [comment]
@silvolu @bcoe is this on the roadmap?

**Comment by oelbaga** [comment]
So you can't use oAuth to pull data? only a service account? Can't be.

**Comment by Pjrogu224** [comment]
I am also trying to access through oAuth. I can't find any info on it?

**Comment by LindaLawton** [comment]
This is my sample [google_analytics_data_oauth_quickstart.js](https://gist.github.com/LindaLawton/87ce3793d6782731612350774cc4a757)

**Comment by danielbankhead** [comment]
We have a few different ways to instantiate an [`OAuth2Client`](https://github.com/googleapis/google-auth-library-nodejs/blob/e31a831417692e730f79d42608bd543046070ae3/src/auth/oauth2client.ts#L515):
- https://github.com/googleapis/google-auth-library-nodejs/tree/main?tab=readme-ov-file#oauth2

The APIs in this repo allow this client to be passed via the `authClient` option during construction (or via `auth` if using a `GoogleAuth` instance). For example:
```ts
import {StorageTransferServiceClient} from '@google-cloud/storage-transfer';

new StorageTransferServiceClient({
  'authClient': new OAuth2Client()
});
```

**Comment by thisisrachelramos** [comment]
For those searching, this is related to https://github.com/googleapis/nodejs-analytics-data/issues/41
Which is archived so I cannot comment there.

@danielbankhead suggestion is the move here, appreciate it!
