### ISSUE TITLE
New Samples Not Copy-Pastable

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-node#2906]
This may beg for a lengthier discussion somewhere else, but I'm filing it as a bug here just in case it counts as one. 

All the code samples in `/samples` now use `await`, but `await` is only valid in async function, which means that the samples can't be run if someone just copies and pastes the code. This is different from what we are striving for across all our samples.

**Comment by jmdobry** [comment]
I hope to have this finalized in the coming days.
