### ISSUE TITLE
Only .addOnFailureListener Method is executing Why?

### ISSUE THREAD

**Issue by Prajith-Shriman** [googleapis/google-cloud-node#2907]
FirebaseVisionImage image = FirebaseVisionImage.fromBitmap(bitmap);

FirebaseVisionImageLabeler labeler = FirebaseVision.getInstance()
    .getCloudImageLabeler();

labeler.processImage(image)
    .addOnSuccessListener(new OnSuccessListener<List<FirebaseVisionImageLabel>>() {
      @Override
      public void onSuccess(List<FirebaseVisionImageLabel> labels) {
        // Task completed successfully
        // ...
        for (FirebaseVisionImageLabel label: labels) {
  String text = label.getText();
  String entityId = label.getEntityId();
  float confidence = label.getConfidence();
}

      }
    })
    .addOnFailureListener(new OnFailureListener() {
      @Override
      public void onFailure(@NonNull Exception e) {
        // Task failed with an exception
        // ...
      }
    });

**Comment by callmehiphop** [comment]
This repo is for Node.js client libraries, so I don't think this is the best place to get your question answered. Unfortunately I don't know where the correct place is, @JustinBeckwith would you be able to point @Prajith-Shriman in the right direction?
