### ISSUE TITLE
TypeScript Conventions

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-node#2908]
Jumping from repo to repo, sometimes I'm surprised to see that our TypeScript conventions can sometimes vary quite a bit. I think it would be great if we could somehow standardize how we write TS with something like a style guide.

I started a doc to call out some stuff I think we should avoid doing, as well as some things I think we could probably do better. I am by no means a TypeScript expert, so if something looks incorrect, it very well might be. I'm just trying to get the ball rolling on getting a consistent experience across all our libraries.

https://docs.google.com/document/d/16QH68B3KMDrvaya0_Zyqz9YzLps-9hjX1AIMM3WIgtU/edit

**Comment by JustinBeckwith** [comment]
This is all goodness.  I left a few comments. A few things to consider:
- We should publish this guide here in a markdown file to make it easier to reference and update IMO
- After we have broad agreement, I'd like to see individual bugs to track some of these down across repos

**Comment by callmehiphop** [comment]
SGTM, I actually started in markdown so with a few small edits I can have that ready for us. Should we put it in the repo Wiki?

**Comment by bcoe** [comment]
I think we should continue to iterate on gts, and use this as a tool for enforcing our TypeScript best practices.
