### ISSUE TITLE
Should we be using hard-rejection?

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2910]
In some of our repos, we use the `hard-rejection` module during unit tests to ensure we don't allow rejected promises in passing tests.  However - I *think* the `--throw-deprecation` flag we use in our shared mocha options should protect us, since unhandled promise rejections are treated as throws. 

@bcoe what's your feel on this one?  I found 5 of our repos that use this, and it's all for unit tests.  Should we drop this dep?

**Comment by bcoe** [comment]
there's actually some work happening in Node.js right now on this topic:

**Comment by BridgeAR** [comment]
@JustinBeckwith the flag is going to protect you in case no `unhandledRejection` hook is attached (there won't be any deprecation warning in case the hook is used and therefore the flag won't have any effect). I recommend to use the `hard-rejection` module as well.

@bcoe I will try to backport the functionality down to Node.js 8 but that might take a while.

**Comment by bcoe** [comment]
@BridgeAR if we do backport your work to all active release lines, what would the advantage be of using `hard-rejection` over `NODE_OPTIONS=--unhandled-rejections=strict`? (out of curiosity).

**Comment by BridgeAR** [comment]
You can use the module right away while the only backport minors from time to time, so it'll take a while until this lands in the releases.

**Comment by JustinBeckwith** [comment]
Since I don't think we have immediate plans here, I'm closing this out ✌️
