### ISSUE TITLE
Drop usage of `through2` and `@types/through2`

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2911]
With the upcoming node6 deprecation, we *should* be able to use the `PassThrough` stream that's available in node core.  I'd love to lose the requirement of user space streams, and this would be a fine first step.  

@stephenplusplus especially interested in your streams expertise here :) Is this a feasible thing for us to go do?

**Comment by bcoe** [comment]
@soldair has done more with streams than anyone else I worked with at npm, would be worth getting his opinion of `PassThrough` vs `through2`.

**Comment by soldair** [comment]
through2 has become much smaller than it used to be.
https://github.com/rvagg/through2/blob/master/through2.js

It depends on readable-stream which is supposed to be exactly node core's streams in userland.

It's notable differences are that it uses a high water mark of 16 when creating the object stream and adds a destroy method that may emit error and emits close.

I don't think that i have work around's for any specific quirks or things that would block moving ahead with this.

changing may impact browser bundling users but most include their own copy of node core streams when needed anyway.

**Comment by JustinBeckwith** [comment]
> It depends on readable-stream which is supposed to be exactly node core's streams in userland.

While true, I'm more concerned with the load time associated with pulling it in.  30ms is 30ms.
https://npmtrace.appspot.com/packages/through2/3.0.1

**Comment by soldair** [comment]
Yeah I support saving require time. It'll be a major wherever we return a stream to users but that's just a number.

**Comment by JustinBeckwith** [comment]
I think we've done most of what we can do here for now.  I'm just going to close this out, as it's not actually causing a ton of trouble.
