### ISSUE TITLE
Remove request.Response references

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-node#2913]
In a number of places we reference the `request.Response` type ([example](https://github.com/googleapis/nodejs-storage/blob/master/src/bucket.ts#L155)). This type refers to the raw response, but typically we return the response body where it is used.

**Comment by JustinBeckwith** [comment]
There are a couple of outstanding PRs still floating around, but I'm comfortable calling this one done :) @callmehiphop if you see other cases of this, can you open issues on the individual repos?  I think I got them all, but 🤷‍♂
