### ISSUE TITLE
better nyc default configuration

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#2914]
there are a few shortcomings in how nyc is configured by default in synthtool:

## we don't display coverage when someone is running tests locally

right now we only generate the lcov report on disk, we should also output human readable information.

## we don't show files unless they have tests written for them

we can address this issue by running with `--all`, but there's a bug with `nyc` currently that stops this from working (I am volunteering to fix this upstream).

**Comment by JustinBeckwith** [comment]
Pretty sure we landed this!
