### ISSUE TITLE
update eslint rules to prefer single quotes

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2915]
I was reading a bit of PR feedback over here, where the developer used backticks over single quotes, when not strictly necessary:
https://github.com/googleapis/nodejs-translate/pull/234/files#r271541085

If this is our story (as I think it should be), we should update our default eslint rules to enforce this via the linter:
https://eslint.org/docs/rules/quotes

**Comment by bcoe** [comment]
@JustinBeckwith can we address this with https://github.com/google/gts/pull/421

**Comment by JustinBeckwith** [comment]
Of course!

**Comment by bcoe** [comment]
Published in `gts@2.0.0-alpha.9`.
