### ISSUE TITLE
Find a way to ensure all tests are actually run

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2916]
Looking at the PR here:
https://github.com/googleapis/nodejs-translate/pull/234/files

There was an attempt to update the sample tests to do this:
```
mocha system-test system-test/v3beta1/ --timeout 90000
```

If I hadn't of noticed this on a drive by code review, we would have stopped testing every sample in that repo aside from the ones.  We should use an eslint rule to make sure that's not happening, if at all possible.  Not sure if this exists 🤷‍♂️

**Comment by bcoe** [comment]
we are in the process of overhauling how we think about sample smoke tests, making this old issue stale.
