### ISSUE TITLE
better document what libraries work in front-end/how to use libraries on the front-end

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#2918]
## Problem

People don't understand that a compilation step prevents them from being able to use some libraries on the front-end; folks try to pull dependencies like [@google-cloud/speech](https://github.com/googleapis/nodejs-speech/issues/331) into React components, as an example, and the webpack error they receive is cryptic.

## Long term solution

There's already awesome work in process by folks like @eoogbe and @alexander-fenster to reduce our reliance on compiled node.js libraries over time (hooray \o/).

But, it will take a while to reach this vision of the future.

## Stop Gap Solution

It would be nice to be able to demonstrate to people how they might still use some of our compiled libraries in web applications...

What if we added samples to some of our more popular GAPIC libraries that demonstrates how to build a simple client/server applications that interacts with them?

**Comment by alexander-fenster** [comment]
Note 1: for the time being (while GAPIC libraries are server-side only), we can direct people to use [googleapis](https://www.npmjs.com/package/googleapis) package which can be used in browser. This is worse in terms of usability but an acceptable alternative.

Note 2: even when we start fully supporting GAPIC libraries in browser using [gRPC-Web](https://github.com/grpc/grpc-web), some gRPC functionality (client streaming calls) will never be supported (until gRPC-Web implements it).

**Comment by bcoe** [comment]
an update, triaging issues today there were at least 5 that related to folks not understanding that various Node.js libraries that were installed couldn't webpack.

@alexander-fenster I love your idea of calling out the fact (in our READMEs  perhaps?) that `googleapis` is an alternative to the GAPIC libraries); I also think calling out in general in our READMES the fact that some of our libraries (in `googleapis` as well) won't necessarily work in he browser.

**Comment by busunkim96** [comment]
I don't think this would be applicable to all languages (just node.js?). If we do put this information in `.repo-metadata.json`, it would probably be a good time to specify how language specific information gets added with a json schema.

**Comment by bcoe** [comment]
@busunkim96 I agree, the frontend/backend dichotomy really only comes up in JavaScript right? I wonder if we could look for the `gapic` dependency when generated docs?

**Comment by bcoe** [comment]
We are working on an RFC to address the problem of a Web SDK more holistically.
