### ISSUE TITLE
Use a supported jsdoc template

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2926]
Today in our JavaScript packages, we're using this template:
```
"jsdoc-baseline": "git+https://github.com/hegemonic/jsdoc-baseline.git",
```

Taking a look at the [repo](https://github.com/hegemonic/jsdoc-baseline), it looks to be ... not maintained.  We are starting to see npm audit advisories for out of date transitive dependencies.  We need a plan to either:
- maintain the template we're using or 
- pick one that's well supported

@jmdobry @jkwlui thinking y'all have more context than me here :)  @bcoe for FYI.

**Comment by jkwlui** [comment]
+1. jsdoc-baseline was great because it's easily customisable to cloud.google.com.
We should move to a one with better support once we move away!

**Comment by jmdobry** [comment]
Yes, `hegemonic/jsdoc-baseline` is what enables the Node.js reference docs to live on cloud.google.com. Once you move to your new site, use whatever template you like. I imagine hegemonic@ would be willing to publish an update for you or make you a collaborator so you can do it.

**Comment by JustinBeckwith** [comment]
@hegemonic 👋 Looking for any contributors to https://github.com/hegemonic/jsdoc-baseline?  Or is there a different basic template we should be using?

**Comment by hegemonic** [comment]
I’m catching up on a lot of JSDoc maintenance right now, and `jsdoc-baseline` is next on my list. I’ll update its dependencies in the next week or so.

As requested by @bcoe, I’ll also publish the package to npm, so you don’t have to keep pulling it in directly from GitHub.

**Comment by JustinBeckwith** [comment]
Just to be clear - I'm more than happy to help here if you're looking for maintainers!

**Comment by bcoe** [comment]
@hegemonic :+1: very much appreciated; and like @JustinBeckwith says, please let us know if there's any way we can help.

**Comment by hegemonic** [comment]
OK, I just published version 0.1.0 of the template to npm: https://www.npmjs.com/package/jsdoc-baseline

Version 0.1.0 uses up-to-date dependencies with no vulnerabilities. It works with Node.js >=8, and it expects `"jsdoc": "^3.6.2"` as a peer dependency.

Thanks for the offers of assistance! I think I'm in good shape, but I'll let you know if I fall behind again and need a hand.

**Comment by JustinBeckwith** [comment]
Thanks @hegemonic!

**Comment by JustinBeckwith** [comment]
We're all good here now :)
