### ISSUE TITLE
"Using the client library" simply links to code

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2927]
This was feedback from @grant over in https://github.com/googleapis/nodejs-tasks/issues/227.  I created this as a meta tracking issue for how we product our sample README files. 

-----

Before you begin ("Before running the samples, make sure you've followed the steps outlined in Using the client library."
The link to "Using the client library" simply links to code. There are no steps. How do I follow them?

**Comment by grant** [comment]
After a revisit of the issue, this seems fine now.
