### ISSUE TITLE
Provide `apiEndpoint` override option 

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2928]
For each API, we should support overriding the API endpoint to be used via the `apiEndpoint` property passed into the constructor options.  

High level blocking issues:
- [x] https://github.com/googleapis/nodejs-common/pull/427
- [x] https://github.com/googleapis/gapic-generator/issues/2787

Per-API issues:
- [x] [googleapis/cloud-debug-nodejs](https://github.com/googleapis/cloud-debug-nodejs/pull/713)
- [ ] [googleapis/cloud-profiler-nodejs](https://github.com/googleapis/cloud-profiler-nodejs/pull/509)
- [ ] googleapis/cloud-trace-nodejs
- [x] [googleapis/gce-images](https://github.com/googleapis/gce-images/pull/155)
- [x] [googleapis/gcs-resumable-upload](https://github.com/googleapis/gcs-resumable-upload/pull/230/)
- [x] googleapis/google-api-nodejs-client
- [x] googleapis/google-cloud-kvstore
- [x] [googleapis/nodejs-bigquery](https://github.com/googleapis/nodejs-bigquery/pull/455)
- [ ] googleapis/nodejs-bigtable
- [x] [googleapis/nodejs-compute](https://github.com/googleapis/nodejs-compute/pull/322/)
- [x] googleapis/nodejs-datastore
- [x] [googleapis/nodejs-dns](https://github.com/googleapis/nodejs-dns/pull/272)
- [ ] googleapis/nodejs-error-reporting
- [x] googleapis/nodejs-firestore
- [x] [googleapis/nodejs-logging](https://github.com/googleapis/nodejs-logging/pull/501)
- [x] [googleapis/nodejs-logging-bunyan](https://github.com/googleapis/nodejs-logging-bunyan/pull/336)
- [x] [googleapis/nodejs-logging-winston](https://github.com/googleapis/nodejs-logging-winston/pull/352)
- [x] googleapis/nodejs-pubsub
- [x] [googleapis/nodejs-rcloadenv](https://github.com/googleapis/nodejs-rcloadenv/pull/86)
- [x] [googleapis/nodejs-resource](https://github.com/googleapis/nodejs-resource/pull/229)
- [x] [googleapis/nodejs-spanner](https://github.com/googleapis/nodejs-spanner/pull/634)
- [x] [googleapis/nodejs-translate](https://github.com/googleapis/nodejs-translate/pull/285)
- [x] [googleapis/nodejs-storage](https://github.com/googleapis/nodejs-storage/pull/728/)

### GAPIC generated
- [x] googleapis/nodejs-asset
- [x] googleapis/nodejs-automl
- [x] googleapis/nodejs-bigquery-data-transfer
- [x] googleapis/nodejs-cloud-container
- [x] googleapis/nodejs-containeranalysis
- [x] googleapis/nodejs-datalabeling
- [x] googleapis/nodejs-dataproc
- [x] googleapis/nodejs-dialogflow
- [x] googleapis/nodejs-dlp
- [x] googleapis/nodejs-iot
- [x] googleapis/nodejs-irm
- [x] googleapis/nodejs-kms
- [x] googleapis/nodejs-language
- [x] googleapis/nodejs-monitoring
- [x] googleapis/nodejs-os-login
- [x] googleapis/nodejs-recaptcha-enterprise
- [x] googleapis/nodejs-redis
- [x] googleapis/nodejs-scheduler
- [x] googleapis/nodejs-security-center
- [x] googleapis/nodejs-speech
- [x] googleapis/nodejs-talent
- [x] googleapis/nodejs-tasks
- [x] googleapis/nodejs-text-to-speech
- [x] googleapis/nodejs-web-risk
- [x] googleapis/nodejs-video-intelligence
- [x] googleapis/nodejs-vision

**Comment by stephenplusplus** [comment]
We used to have this in common! Did we lose it?

**Comment by JustinBeckwith** [comment]
Oh bother - I appear to have missed this one 😆 I see that we handle the `customEndpoint` property in the `MakeAuthenticatedRequestConfig` interface, but it I don't think (need to look deeper) it's actually documented in any of the jsdoc or interfaces we provide.  The hand written libs that sit over nodejs-common-grpc *do* provide this, but kinda all handle it manually.

The plan is different based on the type of lib, but my thinking was that in the ones that sit on `nodejs-common` we would do something like this:


```js
constructor(options: StorageOptions = {}) {
   options.apiEndpoint = options.apiEndpoint ||'www.googleapis.com';
   const config = {
     baseUrl: `https://${options.apiEndpoint}/storage/v1`,
     projectIdRequired: false,
     scopes: [
       'https://www.googleapis.com/auth/cloud-platform',
       'https://www.googleapis.com/auth/devstorage.full_control',
     ],
     packageJson: require('../../package.json'),
   };
   super(config, options);
}
```

Does this seem like a good approach?

**Comment by stephenplusplus** [comment]
That looks right to me! We can talk specific implementation when PR time comes, but we might want to make sure to cover also handling them separately, like `host` and `port`.

**Comment by JustinBeckwith** [comment]
We got all of this covered 👍
