### ISSUE TITLE
Normalize samples

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-node#2930]
I've noticed a few small discrepancies between samples across some of our repos. Maybe we don't care, but I figured I'd start a discussion on the off chance that we do.

In [some samples](https://github.com/googleapis/nodejs-tasks/blob/master/samples/listQueues.js), the main function itself is `async` and when we call it we attempt to `catch` and print any errors that may occur.

In [others](https://github.com/googleapis/nodejs-bigquery/blob/master/samples/listDatasets.js) the main function is not async, instead an inner function is, and there is no error handling in addition to that.

I would *think* that the former is preferred, but I've been largely out of the loop in regards to samples and as far as I know there is not a spec publicly shared.

**Comment by meredithslota** [comment]
https://github.com/googleapis/nodejs-tasks/pull/475 addressed bringing the Tasks samples up to current standards, and we are also working on a public Github-hosted sample guide (and most API-specific samples have migrated to the client library repo, e.g. https://github.com/googleapis/nodejs-tasks/tree/main/samples). I'm closing this out for now.
