### ISSUE TITLE
Cloud Run API

### ISSUE THREAD

**Issue by iancrowther** [googleapis/google-cloud-node#2941]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I would like to manage cloud run via node
A new API Library released
I have looked at the REST client

**Comment by ekuzu** [comment]
Hi Guys,
First of all thanks for this great gcloud nodejs libs, i just want to know what is your plan or road map for google cloud run nodejs library.
Thanks.

**Comment by JustinBeckwith** [comment]
Greetings @ekuzu!  We plan to build this, but we don't have a timeline just yet.  In the meantime: you can actually use the `googleapis` npm module to work with the Cloud Run API today!
https://github.com/googleapis/google-api-nodejs-client/

**Comment by iancrowther** [comment]
oh cool - thanks @JustinBeckwith

**Comment by remorses** [comment]
For reference i managed to use the googleapis to use cloud run, however keep i mind that it is auto generated and miss completely any sort of tests, indeed i found some "bugs":
- you have to provide a different `rootUrl`, the default one is wrong
- you cannot set the `rootUrl` because of a bug, it changes the url in unpredictable manner
- you have to read the rest api documentation because some things aren't obvious, like the in this case the name option must be `namespaces/${namespace_id}/services/${service_id}`
```ts
import { run_v1, google } from 'googleapis'

const defaultOptions = {
    rootUrl: 'https://us-central1-run.googleapis.com', // can use different region if you want
}

const CREDENTIALS = {}

const main = async () => {
    const auth = new google.auth.GoogleAuth({
        scopes: ['https://www.googleapis.com/auth/cloud-platform'], // doesn't work without this
        credentials: CREDENTIALS, // you can omit to use creds from environement
    })
    const authClient = await auth.getClient()
    const run = new run_v1.Run({
        auth: authClient,
    })
    try {
        const namespace_id = 'projectId'
        const service_id = 'servicename'
        const x = await run.namespaces.services.get(
            {
                name: `namespaces/${namespace_id}/services/${service_id}`,
            },
            defaultOptions,
        )
        console.log(x)
        console.log('DATA')
        console.error(JSON.stringify(x.data, null, 4))
    } catch (e) {
        // console.error(e)
        console.error(JSON.stringify(e, null, 4))
    }
})

```

**Comment by kostenickj** [comment]
any ETA on when this might be available?

**Comment by JustinBeckwith** [comment]
Greetings folks!  As of now, the plan is to _not_ build a library here.  The reasoning was that the libraries should be the same between Cloud Run and KNative.  The toolchain we have today assumes the service runs in GCP, and makes a lot of assumptions about grpc, authentication, and Google's general API platform.  

I'm adding @steren who can speak to Cloud Run and it's APIs, and @mattmoor who can speak to KNative specific SDKs you should be able to use.  

Of course, feedback on the approach always welcomed :)

**Comment by steren** [comment]
@remorses thanks for the feedback on https://github.com/googleapis/google-cloud-node/issues/2941#issuecomment-599235742
Would you mind opening an issue on https://github.com/googleapis/google-api-nodejs-client/ about this?

**Comment by danielmahon** [comment]
Is this still planned to merge with KNative? I just spent the last few hours banging my head against the table trying to the get `@google-cloud/run` to work as it's listed here: https://cloud.google.com/nodejs/docs/reference. But no matter my configuration I kept getting back gRPC UNIMPLEMENTED errors when trying to `listServices` for example. The link should be removed from the reference page if the package is abandoned, else it definitely better documentation as I could not get it to work. I was able to get the list via `googleapis` however.

**Comment by bcoe** [comment]
There is now a Clou Run API 🎉 

https://github.com/googleapis/nodejs-run

As @danielmahon describes, there is however a bug with this API, being tracked here:

https://github.com/googleapis/gapic-generator-typescript/issues/1137

--

Closing this issue, as the API is now generated. Follow along in 1137, and a fix should be out soon.

**Comment by alexander-fenster** [comment]
Everything should be fixed, I just released https://www.npmjs.com/package/@google-cloud/run/v/0.2.1.
