### ISSUE TITLE
Update MultiRegional and Regional to Standard

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-node#2945]
(I don't have assign privileges in this repo but this should be assigned to @stephenplusplus  )

Previously, we implemented the concept of "Location Type" to move the concept of bucket location away from storage class. It is no longer considered correct to use "MultiRegional" or "Regional" as a storage class, instead those should be location types.

As such, we need to update every instance of the "MultiRegional" and "Regional" storage in samples, library documentation, and tests to use "Standard" instead--Standard is a correct storage class.

Note that "MultiRegional" and "Regional" should only be replaced with "Standard" in cases where they are used a storage class. If they're used as a location type, that's fine and doesn't need to be replaced.

https://github.com/googleapis/nodejs-storage/blob/213a88d7b9969fe684b311c3668189989e61aae4/src/file.ts#L3170
https://github.com/googleapis/nodejs-storage/blob/4336882b381fc8f7909cf602b94f4cb92f9ea7b6/src/bucket.ts#L2770
https://github.com/googleapis/nodejs-storage/blob/4336882b381fc8f7909cf602b94f4cb92f9ea7b6/system-test/storage.ts#L957
https://github.com/googleapis/nodejs-storage/blob/61eeb64a6bca194361aacf2a312d27d0e6d63b35/test/index.ts#L334

**Comment by JustinBeckwith** [comment]
@JesseLovelace please go file this in https://github.com/googleapis/nodejs-storage/ :)
