### ISSUE TITLE
enum type in protos isn't well represented in reference docs

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#2946]
see: https://github.com/googleapis/nodejs-vision/issues/439

In a variety of places I believe the string representation of proto enums is used, e.g., `LIKELY`, `VERY_LIKELY`, in the vision API, however, the docs indicate an integer return type. It would be nice if enums were better described in documentation.

In general, it's a bit confusing that a string is treated as an `enum`, it might be worth instead having actual types, like `Likelihood.LIKELY`, `Likelihood.VERY_LIKELY`.

**Comment by cedvdb** [comment]
The typecript definition of the likelyhood is : 

`google.cloud.vision.v1.Likelihood | "UNKNOWN" | "VERY_UNLIKELY" | "UNLIKELY" | "POSSIBLE" | "LIKELY" | "VERY_LIKELY" | null | undefined`

Which makes it very confusing, and the official example themselves are wrong if that typing is correct.

To check if something is unlikely one has to check that:

```
safeSearchResult?.adult == 'VERY_UNLIKELY' || safeSearchResult?.adult == google.cloud.vision.v1.Likelihood.UNLIKELY
```

Just use an enum value or a string but don't use both it's unnecessary confusing.

**Comment by sofisl** [comment]
This is very late, I *believe* this has been fixed, at least it's no longer listed as a string (rather as an enum): https://cloud.google.com/nodejs/docs/reference/vision/latest/vision/protos.google.cloud.vision.v1.faceannotation-class

I may be misunderstanding your original problem though, if so please let me know if so.

**Comment by cedvdb** [comment]
@sofisl 

![image](https://github.com/user-attachments/assets/4456c6f1-ff85-4dd5-9816-d285a43b1589)

**Comment by cedvdb** [comment]
It was answered the comment before
