### ISSUE TITLE
make README auto-generate nightly with synthtool

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#2954]
@busunkim96 if I I add a synth.py, will this jus start working? I think we just need to run a shell command to kick off the generation.

**Comment by busunkim96** [comment]
I think so! It looks like Autosynth is already looking tracking this repo since it's included in sloth's list. Could you take a peek at [this script](https://devrel.git.corp.google.com/cloud/libraries/tools/autosynth/+/master/autosynth/providers/nodejs.py) to confirm?
