### ISSUE TITLE
Add CI for node.js 13

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2957]

**Comment by bcoe** [comment]
I've written up a document describing our Node.js version support policy in a holistic way, i.e., how we'll approach upgrading Node.js versions in the future, I think we can probably close this issue and instead agree that we'll be coordinating with other teams at Google, and making an effort to follow Node.js' release cycle? swapping CI in and out as it's upgraded.

**Comment by JustinBeckwith** [comment]
For deprecations, sure.  For new versions, I think we should stay on top regardless of what partner teams are doing.

**Comment by JustinBeckwith** [comment]
Pretty sure this is done :)
