### ISSUE TITLE
Reference doc publication needs to work with GitHub app

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#2961]
Currently, the publication of reference docs is kicked off by the `publish` kokoro job, as we start to move publication towards our new GitHub-app-based approach for publication, we need to figure out how we're going to kick off this job (perhaps we could just move it to being nightly?).

**Comment by JustinBeckwith** [comment]
👋 I would very much prefer the docs to get published along with the package, and not relying on a cron job.  Otherwise, folks get into the situation where they `npm install` the library, and the ref docs can just be wrong.

**Comment by bcoe** [comment]
one current thought is perhaps we could kick off a kokoro job from the GitHub app.

**Comment by JustinBeckwith** [comment]
@bcoe checkin in - we moved completely over to the GitHub app for publishing.  Is this still broken?

**Comment by bcoe** [comment]
👍 fixed, we're completely moved over as of late last week.
