### ISSUE TITLE
Use Node.js to call Google API and put it into a cloud function. client method cannot return data

### ISSUE THREAD

**Issue by yeuuaeh** [googleapis/google-cloud-node#2964]
`const listDevicesForGateway = async (client,projectId,cloudRegion,registryId,gatewayId) => {
const parentName = projects/${projectId}/locations/${cloudRegion}/registries/${registryId};
const request = {
parent: parentName,
'gatewayListOptions.associationsGatewayId': gatewayId,
};
let devices;
try {
const {data} = await client.projects.locations.registries.devices.list(
request
);
devices = data.devices;
} catch (err) {
console.error('Could not list devices', err);
return;
}
console.log('Current devices bound to gateway: ', gatewayId);
if (devices && devices.length > 0) {
devices.forEach(device => {
console.log(\tDevice: ${device.numId} : ${device.id});
});
} else {
console.log('No devices bound to this gateway.');
}
};`

const {data} = await client.projects.locations.registries.devices.lis cannot return data.
I try to use const client = new iot.v1.DeviceManagerClient to get part of the API function data, but I can't implement other API functions to deploy to cloud functions

Thanks for help, urgent help!

**Comment by yeuuaeh** [comment]
![image](https://user-images.githubusercontent.com/34910206/72058224-b229e100-330a-11ea-969e-0fa8cca628af.png)

This client library method cannot return data.

**Comment by yeuuaeh** [comment]
@proppy @stephenplusplus @lukesneeringer

**Comment by bcoe** [comment]
@yeuuaeh it might be worth taking a look at our [@google-cloud/iot](https://github.com/googleapis/nodejs-iot) library, which provides fairly detailed instructions for getting up and running with an authenticated client.

**Comment by yeuuaeh** [comment]
@bcoe Thank you for your answer, I tried the google-cloud / iot-Node.js package to implement a unique API, but some functions are not provided on the google-cloud / iot source code, and can only implement ordinary device registration , Delete, modify. What can't be achieved, such as adding a gateway and communication with the device, MQTT connection, but I encountered a problem during the Mqtt connection process, why can't I read the connected device using the google-cloud / iot-Mqtt method. Hope you can help me see.
code show as below:
![image](https://user-images.githubusercontent.com/34910206/72213030-75383700-3522-11ea-8394-e8829bdc159d.png)
@bcoe

**Comment by bcoe** [comment]
@yeuuaeh if I"m understanding correctly, you are receiving no results when calling `registries.list`?

**Comment by yeuuaeh** [comment]
@bcoe Yes, for example, I need to bind the device to the gateway and register the gateway, but there is no method to directly call the API under the @ google-cloud / iot library Node.js package, and the source code and official instance are also client.probjects.locations .registries.list, this way request the client, but has been unable to return to the data.

**Comment by bcoe** [comment]
I think this is similar to the issue being discussed [here](https://github.com/googleapis/google-api-nodejs-client/issues/1929), so it doesn't relate directly to the client libraries (since you're using MQTT); the advice was to open a StackOverflow question, and it sounds like folks can help people there :+1: 

Hopefully this gets you moving in the right direction :+1:
