### ISSUE TITLE
Node 8 deprecation party 🎉

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#2972]
For reference, [here's a PR adding the new gts](https://github.com/googleapis/nodejs-promisify/pull/183).

# Wave 1: (Day 1)

- [x] googleapis/gaxios (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/google-p12-pem **(@bcoe)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-promisify **(@bcoe)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-paginator (@summer-ji-eng )
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-precise-date (@summer-ji-eng )
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-projectify **(@AVaksman)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/release-please **(@xiaozhenliu-gg5)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/github-repo-automation **(@xiaozhenliu-gg5)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/repo-automation-bots  **(JustinBeckwith )**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/sloth  **(@xiaozhenliu-gg5)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/teeny-request **(Summer)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/gapic-generator-typescript **(@xiaozhenliu-gg5)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts

# Wave 2 (Day 1)
- [x] googleapis/node-gtoken **(bcoe)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/gcp-metadata **(bcoe)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-proto-files **(@AVaksman)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts

# Wave 3 (Day 1)
- [x] googleapis/google-auth-library-nodejs **(@bcoe)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts

# Wave 4 (Day 1)
- [x] googleapis/nodejs-googleapis-common **(@sofisl)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-gce-images **(@steffnay)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/gcs-resumable-upload [@summer-ji-eng ]
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/gax-nodejs @alexander-fenster 
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-common  
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts

# Wave 5: fair game

- [x] googleapis/cloud-debug-nodejs **(@AVaksman)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/google-api-nodejs-client [@summer-ji-eng ]
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/google-cloud-node @sofisl 
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-asset **(@xiaozhenliu-gg5)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-automl **(@bcoe)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-bigquery-data-transfer 
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-bigtable @alexander-fenster 
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-billing (@sofisl says that it looks done to her, though she didn't do it...)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-billing-budgets (@sofisl says that it looks done to her, though she didn't do it)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-cloud-container **(@AVaksman)**
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-cloudbuild (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-compute (@sofisl)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-containeranalysis (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-datacatalog (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-datalabeling (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-dataproc (@sofisl says that it looks done to her, though she didn't do it 👍 )
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-dialogflow
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-dlp (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-dns (@sofisl)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] GoogleCloudPlatform/nodejs-docs-samples (@sofisl)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-document-ai (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-error-reporting (@sofisl)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-game-servers (@sofisl says that it looks done to her, though she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-getting-started (@steffnay) (Does not exist?)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-grafeas (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-iot (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-irm (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-language (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-monitoring [@summer-ji-eng ]
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-monitoring-dashboards
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-os-login (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-phishing-protection (@bcoe)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-rcloadenv
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-recaptcha-enterprise
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-recommender
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-redis
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-resource
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-scheduler
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-secret-manager [@summer-ji-eng ]
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-security-center 
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-service-directory
  - [x] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-speech
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-talent
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-tasks
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-text-to-speech
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-video-intelligence [@summer-ji-eng ]
  - [x] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-web-risk
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts

## Wave 6: fair game once wave 5 is done

- [x] googleapis/nodejs-datastore-kvstore
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-datastore-session(@steffnay) [JS library]
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-logging-bunyan (@sofisl says this looks done to her. Submitted a pr with some small updates, but the library was already updated).
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-logging-winston (@sofisl says this looks done to her, she didn't do it.)
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts

## Wait for go ahead from @bcoe 

- [x] googleapis/nodejs-bigquery-storage
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-storage
  - [x] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-pubsub
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-logging
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-bigquery
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-datastore
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/cloud-trace-nodejs
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-vision 
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/nodejs-kms
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts
- [x] googleapis/cloud-profiler-nodejs
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-translate
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [x] googleapis/nodejs-spanner
  - [x] engines updated
  - [x] typescript updated
  - [x] create legacy-8 tag
  - [x] update gts

## Wait for go ahead from Sebastian and Firebase Team

- [ ] googleapis/nodejs-firestore
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts
- [ ] googleapis/nodejs-firestore-session
  - [ ] engines updated
  - [ ] typescript updated
  - [ ] create legacy-8 tag
  - [ ] update gts

**Comment by feywind** [comment]
Async iterator usage?

**Comment by zamnuts** [comment]
As part of TS 3.7 upgrade: optional chaining, nullish coalescing

`http2` now supports ORIGIN frames to enable cross-origin connection reuse, do the GCP servers-side APIs support this optimization?

And for a list of new things, relevant breaking changes or things to watch out for as part of any node 8.x -> 10.x uplift as it relates to googleapis node.js code:

- assert interface changes (may inadvertently fail test cases):
  - `assert.fail` only has 1 arg: https://github.com/nodejs/node/commit/70dcacd710
  - `assert.ifError` only allows `undefined` and `null`, previously truthy was allowed: https://github.com/nodejs/node/commit/e65a6e81ef
  - use native `assert.rejects` and `assert.doesNotReject`: https://github.com/nodejs/node/commit/599337f43e
- `net` now does an explicit `close` after `end`, if workarounds were implemented, this will reveal potential race conditions under load: https://github.com/nodejs/node/commit/9b7a6914a7
- `http2` streams fixed the `destroy`/`end` bug: https://github.com/nodejs/node/pull/24926
- streams:
  - refactor to use `stream.pipeline` where/if applicable
  - if using pause mode, watch for workarounds related to implicit repeat `_read` calls when using `resume` and `read`, this memory bug has been fixed: https://github.com/nodejs/node/pull/26965
- if a promise settles multiple times, warns will be present in this case: https://github.com/nodejs/node/pull/22218

Are we using matrix builds against 8.x and 10.x at the same time? If so, most of this stuff should've already been noticed.

**Comment by bcoe** [comment]
@zamnuts we have had Node 10 in the build matrix for close to a year I think, and I'd bet over 50% of our users are already on Node 10 :+1: 

With regards to improvements, like having optional chaining at our disposal, I think we should use these language features going forward to cleanup our codebases, but a large sweeping refactor shouldn't be part of dropping Node 8 from the testing matrix.

**Comment by bcoe** [comment]
> Async iterator usage?

@feywind, @xiaozhenliu-gg5 came up with a design document which should allow us to add async iterators to Node 10, without it being a breaking change, as soon as 8 is dropped.

So, we're going to use async iterators, which I'm very excited about, but we don't need to get this refactor done for dropping Node 8 (I don't believe).

**Comment by JustinBeckwith** [comment]
I think we're ready to call this party a wrap :) Firestore is the only one left, and they're working independently to get things sorted out.
