### ISSUE TITLE
Codecov reporting is broken

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2974]
In the move to GitHub actions, we broke code coverage reporting to codecov.  GitHub Actions doesn't work magically with the Codecov service, and it requires a key:

1. We need to log into codecov with the yoshi-automation account, and create a user level token
2. I think we should store that token in secret manager
3. I think we should write a bot / cron that can access the secret, and use the GitHub API to set it on all relevant repositories (no org level secrets)
4. I think we need to add something like this to the GitHub Actions coverage script:
`export CODECOV_TOKEN=$(curl -X GET https://codecov.io/api/pub/gh/$GITHUB_REPOSITORY/settings -H 'Authorization: token $CODECOV_API_KEY' | jq -r .repo.upload_token)`

**Comment by bcoe** [comment]
this has been addressed 👌
