### ISSUE TITLE
Readme error? - Firestore Session should be @google-cloud/connect-firestore

### ISSUE THREAD

**Issue by btsimonh** [googleapis/google-cloud-node#3011]
in the readme doc, it references:

Firestore Session | 📓 | npm i @google-cloud/firestore-session | enable | ✔

should this instead be 

Firestore Session | 📓 | npm i @google-cloud/connect-firestore | enable | ✔

That's where the links goes, and then after changing to that, all mentioned APIs install in node.

**Comment by JustinBeckwith** [comment]
Thanks for the heads up!  Fixed in #3015.
