### ISSUE TITLE
docs: "targetting" typo

### ISSUE THREAD

**Issue by TomKristie** [googleapis/google-cloud-node#3019]
In [83 repos](https://github.com/search?q=org%3Agoogleapis+targetting&type=Code), the `README.md` documentation section "Supported Node.js Versions" has a typo "targetting" which should be "targeting"

i.e.

> Client libraries targeting some end-of-life versions of Node.js are available

it should read
> Client libraries targeting some end-of-life versions of Node.js are available

**Comment by jainsamyak** [comment]
Should be fixed by [this](https://github.com/googleapis/synthtool/pull/852)

**Comment by fhinkel** [comment]
Thank you @jainsamyak !
