### ISSUE TITLE
How to use API Keys instead of a service account?

### ISSUE THREAD

**Issue by timcash** [googleapis/google-cloud-node#3025]
Trying to start a compute node using the examples from the compute library but I want to use an API Key so I can have the agent that starts new VM running outside GCP. How do I use an API key from within the client? I tried the following but got an error about the service account. Both env keys are set.

```
const compute = new Compute({
  projectId: process.env.PROJECT_ID,
  key: process.env.GCP_KEY,
});
```

**Comment by JustinBeckwith** [comment]
Greetings!  Most services on GCP don't actually support API keys.  There are some exceptions (Vision and Speech API come to mind), but generally you're going to need to use Service Account Credentials that act on the behalf of a service account or OAuth2 credentials that act on behalf of a user.  you can learn more about the types of auth we support, and a few examples here:
https://cloud.google.com/docs/authentication

If you're looking run run code outside of GCP, you're most likely looking for the Service Account workflow described here:
https://cloud.google.com/docs/authentication/production#manually

I hope this helps!  If you run into any problems, just let us know.
