### ISSUE TITLE
Add ability to include Storage types

### ISSUE THREAD

**Issue by steffnay** [googleapis/google-cloud-node#3026]
In @google-cloud/bigquery we created a custom `File` type where we were supposed to be using a @google-cloud/storage `File` type.  
```
export interface File {
  bucket: any;
  kmsKeyName?: string;
  userProject?: string;
  name: string;
  generation?: number;
}
```
The storage npm module includes these types, but is currently installed as a devDependency. Unless it's included as a production dependency, the types would not be included. The storage module is fairly large, and only really needed for types. It would be ideal to have a way to access these types.

**Comment by JustinBeckwith** [comment]
This is a super interesting problem.  If we shipped separate `@types` packages for our libraries, we would be able to do that, but generally that's not recommended if a library ships it's own types.  I don't know the answer to this one!

**Comment by bcoe** [comment]
@steffnay what happens if you attempt to coerce it into that type?

```
import {File} from '@google-cloud/storage'
fileFromBigQuery as File
```

**Comment by strikingforce909** [comment]
I agree as a typescript dev its a real hassle, maybe you could just add a export to all the types so we can access them like that?

**Comment by danielbankhead** [comment]
It's possible to get this type in `@google-cloud/bigquery` by installing `@google-cloud/storage` importing via [`import type`](https://www.typescriptlang.org/docs/handbook/2/modules.html#import-type):
```
import type {File} from '@google-cloud/storage';
```
or, to force ES Module resolution:
```
import type {File} from '@google-cloud/storage' with {'resolution-mode': 'import'};
```

[Tree shaking](https://developer.mozilla.org/en-US/docs/Glossary/Tree_shaking) should remedy any additional size concerns, now that `@google-cloud/storage` is available in dual module format.

I don't think its feasible to include this type in this library as keeping it consistent with `@google-cloud/storage` would be problematic and could introduce more complex issues.
