### ISSUE TITLE
Visual Search account impersonation

### ISSUE THREAD

**Issue by Mistic92** [googleapis/google-cloud-node#3075]
Hi, to use Visual Search api there need to be generated service account with owner/editor permissions from the same project (let's call it project X). 
We need to access VS api from another project(Y) using service account (A). 

Currently we are generating key fro SA in project X and add it to docker image in project Y. But I found that it should work when using account impersonation. It worked when I did it by hand using gcloud generated access tokens but I can't find how to do this using client library. 
Is there tutorial somewhere?

**Comment by sofisl** [comment]
Hi there! This library doesn't provide any API functionality; it's more of an index of our client libraries.

Perhaps you want to open an issue with a code snippet to reproduce [here](https://github.com/googleapis/nodejs-vision/issues), or more specifically, [here](https://github.com/googleapis/google-auth-library-nodejs) for authentication questions?
