### ISSUE TITLE
@google-cloud/sql-admin library isn't on npmjs

### ISSUE THREAD

**Issue by djvs** [googleapis/google-cloud-node#3107]
#### Steps to reproduce

  1. Go to https://www.npmjs.com/package/@google-cloud/sql-admin
  2. It doesn't exist

It's linked to from https://github.com/googleapis/google-cloud-node but 404s.  Notice the image in README.md says "invalid" on the display too.

**Comment by JustinBeckwith** [comment]
👋  this one is still being put together, and not quite ready for the first publication.  It'll be ready in a few days, but we should still probably update the script to only pull libraries we actually have published to npm :)

**Comment by djvs** [comment]
On a semi-related note, is there documentation for the one on github?  I'm basically drowning trying to implement some calls based on the protos.d.ts right now.

**Comment by JustinBeckwith** [comment]
Ooof, not yet.  You should be able to clone the repository and run `npm run docs` - that would create a `docs/index.html` (I think) that is mostly like what you would see in production.

**Comment by danielbankhead** [comment]
This package is available as [`@google-cloud/sql`](https://www.npmjs.com/package/@google-cloud/sql).
