### ISSUE TITLE
Improve traceability of gRPC errors

### ISSUE THREAD

**Issue by ace-n** [googleapis/google-cloud-node#3118]
**Is this a client library issue or a product issue?**
Client library issue

#### Environment details

  - OS: Mac OS X
  - Node.js version: v12.18.3
  - npm version: 6.14.6
  - `@googleapis/kgsearch` version: ^0.2.0
  - running code via `@google-cloud/functions-framework` version: 1.7.1

#### Steps to reproduce

The `@grpc/grpc-js/build/src/call-stream.js` file (related TypeScript [here](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call-stream.ts#L279-L300)) contains the following code that seems to propagate errors within `process.nextTick()`:

```javascript
outputStatus() {
        /* Precondition: this.finalStatus !== null */
        if (!this.statusOutput) {
            this.statusOutput = true;
            const filteredStatus = this.filterStack.receiveTrailers(this.finalStatus);
            /* We delay the actual action of bubbling up the status to insulate the
             * cleanup code in this class from any errors that may be thrown in the
             * upper layers as a result of bubbling up the status. In particular,
             * if the status is not OK, the "error" event may be emitted
             * synchronously at the top level, which will result in a thrown error if
             * the user does not handle that event. */
            process.nextTick(() => {
                var _a;
                (_a = this.listener) === null || _a === void 0 ? void 0 : _a.onReceiveStatus(filteredStatus);
            });
            if (this.subchannel) {
                this.subchannel.callUnref();
                this.subchannel.removeDisconnectListener(this.disconnectListener);
            }
        }
    }
```

This is (IMHO) an anti-pattern that makes it hard to:
1) Track down which API call caused this error
2) Set up automatic retries (e.g. exponential backoff) on failing calls

I realize this is an issue with the [`grpc-js` repo](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js), but perhaps there's a way _this_ repo can abstract these details away?

#### ~Workaround~
~FWIW, I'm using the following as a temporary workaround to swallow gRPC errors (since my code doesn't need to be production-quality):~

```javascript
process.on('unhandledRejection', (err) => {
  console.log('Unhandled Rejection:', err.stack || err)
})
```

**EDIT:** This workaround didn't work, and neither did `export NODE_OPTIONS=--unhandled-rejections=warn`. 🙁

**Comment by bcoe** [comment]
Looping in @murgatroid99. @ace-n, it might be good to open an issue [here](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) with your feedback, as this is where we work on this part of the system.

**Comment by murgatroid99** [comment]
It's not really clear to me why this `process.nextTick` would cause the problems listed. This code comes after a lot of asynchronous event handlers, so removing that call wouldn't meaningfully change any error's stack trace, and I don't see the relevance to retries at all.

The stack trace can be improved by the suggestions in grpc/grpc-node#1810.

**Comment by ace-n** [comment]
@murgatroid99 what I'm trying to do is auto-retry on an intermittent client library failure.

The problem as I see it is that gRPC errors are divorced from the context that they were thrown in.

For example, I would expect the following to work:

```javascript
(doRetry) => {
  try {
    await flakyApiCall();
  } except (e) {
    doRetry()
  }
}
```

However, it does not - because any errors in `flakyApiCall` appear to be thrown **outside** of the `try...except` context.

**Comment by murgatroid99** [comment]
I can't speak to the async interface. That doesn't exist in the gRPC libraries, so I assume it comes from gax. In the gRPC libraries, errors are not divorced from that context. For unary response methods, errors are in the response callback, and for streaming response methods, errors are emitted in the `error` event on the call object.

**Comment by bcoe** [comment]
@alexander-fenster, I feel like I've bumped into similar behavior to @ace-n. Is there a chance we have an unhandled promise somewhere in google-gax?

**Comment by alexander-fenster** [comment]
I believe the `try { await apiCall(); } catch (err) { ... }` use case works for all known use cases - that means I'm not aware of the case where the error being thrown by an API could not be caught by this. If it happens, it's a bug. @ace-n Can you share the code that I could debug?

**Comment by ace-n** [comment]
Did a VC with @bcoe and @alexander-fenster today.

I think my issue is _in fact_ a duplicate of [this one](https://github.com/googleapis/nodejs-vision/issues/785), so I'll go ahead and close this.
