### ISSUE TITLE
URGENT - Google Cloud Translation APIs started to give our web app on Firebase the strange problem/bug from July 23, 2021

### ISSUE THREAD

**Issue by eGlobeBizCom** [googleapis/google-cloud-node#3124]
Hi All,

We guess that this issue may be related to this forum as well. We posted this issue on the following forum:
https://github.com/googleapis/nodejs-translate/issues/706

Any suggestions and help will be highly appreciated for the above urgent Error Message! Lots of thanks in advance!!

Helen

**Comment by JustinBeckwith** [comment]
Greetings!  No need to open this in both places.  The issue in the translate repo will do.
