### ISSUE TITLE
idea: when we move Node 10 to maintenance write blog post about new features

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#3165]
When we adopt new Node.js versions (in this case `node: >12` in engines, ~April 2022), it would be neat to write a blog post for our library users regarding the slick new Node.js features that are available to them.

**Comment by sofisl** [comment]
Marking it as eol so we can search for the tag and bring up what we should do.

**Comment by danielbankhead** [comment]
A bit swamped - can't get to this anytime soon. I'll release this issue in case someone else has some bandwidth
