### ISSUE TITLE
Images service support

### ISSUE THREAD

**Issue by QTree-app** [googleapis/google-cloud-node#3194]
would be nice to have access to Images service like in [python](https://cloud.google.com/appengine/docs/standard/python/refdocs/google.appengine.api.images).
specifically looking to get a servingUrl.

see [here](https://github.com/googlearchive/appengine-nodejs/issues/37).

thanks!

**Comment by sofisl** [comment]
We autogenerate this library, so for some reason the images service is not exposed to the library. I'll create a bug with the API [here](https://issuetracker.google.com/issues/268114477).
