### ISSUE TITLE
Samples `package.json` configs need stub `package` script

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-cloud-node#3283]
Releases are "failing" (releases are actually succeededing, but samples modules are failing) because `mono-repo-publish` assumes any touched `package.json` file is a releasable library.

We can get around this by having our generated `samples/package.json` files adding an empty `package` script.

See #3262

**Comment by sofisl** [comment]
Solved in https://github.com/googleapis/google-cloud-node/pull/3265
