### ISSUE TITLE
Unable to resolve module http 

### ISSUE THREAD

**Issue by togenius1** [googleapis/google-cloud-node#3390]
I ran its for the React-Native project. 

error: Error: Unable to resolve module http from C:\Users\Finner\Desktop\Mobile-Projects\GoogleServices\examples\OAuth2.tsx: node:http could not be found within the project or in these directories:
  node_modules
   6 | const OAuth2 = (props: Props) => {
   7 |   const {OAuth2Client} = require('google-auth-library');
>  8 |   const http = require('http');
     |                         ^
   9 |   const url = require('url');
  10 |   const open = require('open');
  11 |   const destroyer = require('server-destroy');

**Comment by sofisl** [comment]
Hi @togenius1, I think this is a React-Native issue; it doesn't seem like react-native has the http module. See [here](https://stackoverflow.com/questions/29371694/react-native-and-requirehttp). In the future, we may migrate to fetch.
