### ISSUE TITLE
Hebrew returning iw instead of he

### ISSUE THREAD

**Issue by hazriqpedia** [googleapis/google-cloud-node#3521]
#### Environment details

  - OS: Windows
  - Node.js version: v12.19.0
  - npm version: 6.14.8
  - `@google-cloud/translate` version: 6.2.4

#### Steps to reproduce

  1. tranlate a hebrew phrase (in my case: קוב אחר חבילה)
  ```
   const [detections] = await translate.detect(text)
   const detectedLang = Array.isArray(detections) ? detections[0] : detections
   console.log('detectedLang.language: ', detectedLang.language)
   ```
 
 Getting `iw` as output instead of `he`.
 
 Isn't he is the latest one and should be returned? https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by bcoe** [comment]
Hello @hazriqpedia  this sounds like an issue with the Translate API, vs., the client library.

Could I bother you to instead open the "Translation" issue tracker listed [here](https://cloud.google.com/support/docs/issue-trackers), this will put you in touch with the product team who can help.
