### ISSUE TITLE
Translation not respecting the targeted language, resulting in mixed language translation

### ISSUE THREAD

**Issue by cchen028** [googleapis/google-cloud-node#3522]
Hi all,

I am encountering an issue recently regarding to translation which has been working fine for the past few months.
When I provide an input text (Chinese) , and attempt to translate to one of the languages (Japanese, Korean, French, there could be more but these are the only languages I tested with) , it only translates the first couple lines and the rest is replaced with English translation.

Below is my code for getting the translation:

```javascript
const translateAPI = new Translate({ projectId: process.env.PROJECT_ID, keyFilename: process.env.GOOGLE_APPLICATION_CREDENTIALS });
const [tempTrans] = await translateAPI.translate(text, to);
return he.decode(tempTrans);
```

Please see attached debugged screenshot for the issue.

Below shows the input `text` is in Chinese:
![image](https://user-images.githubusercontent.com/13714216/177205305-02d4ef0e-40dc-4770-80d7-3aa7bcc2efb0.png)

Below shows targeted language is Japanese:
![image](https://user-images.githubusercontent.com/13714216/177204568-708c6cc2-c0da-44db-a7c8-0c86b1872ccf.png)

Below shows the translated language is a mixed of Japanese and English:
![image](https://user-images.githubusercontent.com/13714216/177204670-3825f7fd-5a4e-4ce9-9391-093f497b789c.png)

I have attached the raw input text file. (Input is in Chinese)

When the input text is English, the translation translates as expected, but when the input is in Chinese this issue happens. Any help or advise is appreciated, thanks in advance.
[2022-07-03T00_43_18_742Z-translation-debug-input.txt](https://github.com/googleapis/nodejs-translate/files/9041561/2022-07-03T00_43_18_742Z-translation-debug-input.txt)

#### Environment details
  - OS: Windows
  - Node.js version: Node 10 and 14
  - npm version: 6.14.17
  - `@google-cloud/translate` version: 6.3.1

**Comment by bcoe** [comment]
Hello @cchen028 this sounds like an issue with the Translate API, vs., the client library.

Could I bother you to instead open the "Translation" issue tracker listed [here](https://cloud.google.com/support/docs/issue-trackers), this will put you in touch with the product team who can help.
