### ISSUE TITLE
Javanese language code returning "jw" instead of "jv"

### ISSUE THREAD

**Issue by CambodianCoder** [googleapis/google-cloud-node#3523]
#### Environment details

  - OS: MacOS
  - Node.js version: 16.5
  - npm version: 8.11.0
  - `@google-cloud/translate` version: 6.3.1

#### Steps to reproduce

Based on documentation at https://cloud.google.com/translate/docs/advanced/discovering-supported-languages-v3

  1. Import TranslationServiceClient from "@google-cloud/translate"
  2. Call the function "getSupportedLanguages" on the TranslationServiceClient
  3. Observe that the result for Javanese returns a language code of "jw", instead of "jv" as documented at https://cloud.google.com/translate/docs/languages

<img width="627" alt="image" src="https://user-images.githubusercontent.com/35553625/180490475-522bd3c3-755e-41a3-8399-8b932fe37e58.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/35553625/180490356-b6e3b3a3-1cbf-4d7d-b2b0-d4820c7bbe10.png">

**Comment by bcoe** [comment]
Hello @CambodianCoder, this sounds like it's almost certainly an issue with the upstream API, vs., the client library.

If you open a ticket with the translate product team [here](https://cloud.google.com/support/docs/issue-trackers), it will get you in touch with the right people.
