### ISSUE TITLE
getBuild rejects with not found for a build in a non global region

### ISSUE THREAD

**Issue by thdk** [googleapis/google-cloud-node#3535]
#### Environment details

  - OS: linux
  - Node.js version: 16.17.0
  - npm version: 8.15.0
  - `@google-cloud/cloudbuild` version: 3.1.1

#### Steps to reproduce

```
import { CloudBuildClient } from '@google-cloud/cloudbuild';

// Creates a client
const cb = new CloudBuildClient();

 const [build] = await cb.getBuild({
      id: BUILD_ID,
      projectId: GCP_PROJECT,
 });
```
Above promise gets rejected when the given `BUILD_ID` exists in a non global region. (europe-west1 in my case)

Note: the issue template has some missing replacements as in where to report issues like this one which are likely not specific for the nodejs client library.

**Comment by bcoe** [comment]
Hello @thdk, this sounds most likely as though it's an issue with the upstream API, and not likely something we can fix in the client libraries.

I would open a ticket in the Cloud Build Issue Tracker, listed [here](https://cloud.google.com/support/docs/issue-trackers), which will put you in touch with their product team.
