### ISSUE TITLE
FunctionIds must start with a lowercase letter

### ISSUE THREAD

**Issue by rswlkr** [googleapis/google-cloud-node#3621]
#### Environment details

  - OS: macOS 12.1
  - Node.js version: 16.14.0
  - npm version: 8.3.1
  - `@google-cloud/functions` version: 2.2.0 (V2)

#### Steps to reproduce

  1.  Try to create a function that has a functionId above 4 characters and starting with a non-lowercase letter or a number i.e 62fbb0ce81ac165156e08914 (with this client lib or the rest API).

This will return: 

`'Invalid Request. Violations: {Violation in Function.name=Invalid function_id. Can only contain [-_a-zA-Z0-9] and be between 4-63 characters.}'` 

Irrespective of the reason for the requirement it would useful if there was guidance here to indicate it...updating the regex perhaps..?

**Comment by sofisl** [comment]
@pattishin, I will move this over to nodejs-docs-samples, since it seems like the comments are referring to the samples. Let me know if you disagree, we can reopen over here.
