### ISSUE TITLE
Error: Cannot build HTTP request for {}, method: List

### ISSUE THREAD

**Issue by loganmzz** [googleapis/google-cloud-node#3653]
#### Environment details

  - OS: `Linux Ubuntu`
  - Node.js version: `16.17.1` (LTS)
  - npm version: `8.15.0`
  - `@google-cloud/compute` version: `3.5.0` (latest)

#### Steps to reproduce

  1. `package.json`

```json
{
  "name": "myapp",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "@google-cloud/compute": "3.5.0"
  }
}
```

 2. `index.js`

```js
(async () => {
    try {
        const compute = require('@google-cloud/compute');
        const client = new compute.InstancesClient({
            projectId: process.env.MYAPP_GCLOUD_PROJECT_ID,
            credentials: {
                client_email: process.env.MYAPP_GCLOUD_CREDENTIAL_EMAIL,
                private_key: process.env.MYAPP_GCLOUD_CREDENTIAL_PRIVATE_KEY
            },
        });
        const [vms] = await client.list();
        console.log(vms.map(vm => vm.name));
    } catch (e) {
        console.error('Error with Google Cloud Client Instance', e);
    }
})();
```

  3. `npm i && node index.js`

```text
Error with Google Cloud Client Instance Error: Cannot build HTTP request for {}, method: List
    at encodeRequest (/myapp/node_modules/google-gax/build/src/fallbackRest.js:44:15)
    at Object.serviceStub.<computed> [as list] (/myapp/node_modules/google-gax/build/src/fallbackServiceStub.js:42:35)
    at /myapp/node_modules/@google-cloud/compute/build/src/v1/instances_client.js:225:29
    at wrappedCall (/myapp/node_modules/google-gax/build/src/paginationCalls/pagedApiCaller.js:86:20)
    at Immediate.<anonymous> (/myapp/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16)
    at processImmediate (node:internal/timers:468:21)
```

**Comment by MaksSlesarenko** [comment]
any updates? 
Have same issue with NetworksClient 
Did anyone found way to make it work?

**Comment by loganmzz** [comment]
@MaksSlesarenko 

If you don't want to pass `projectId` variable on each call site, you can retrieve it from `client.getProjectId()`

**Comment by sofisl** [comment]
Hi @loganmzz, thanks for the question! It seems like you'll want to pass in the projectId and the zone, like [so](https://github.com/googleapis/google-cloud-node/blob/3370cf17724fdf1d233c49cb155db68e26227abf/packages/google-cloud-compute/samples/generated/v1/instances.list.js#L68). We have autogenerated samples for all methods [here](https://github.com/googleapis/google-cloud-node/tree/main/packages/google-cloud-compute/samples/generated), plus [handwritten samples here.](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/compute).
