### ISSUE TITLE
UpdatePolicy.minReadySec is supported?

### ISSUE THREAD

**Issue by takaaki7** [googleapis/google-cloud-node#3657]
I couldn't find minReadySec option for rolling update.
Is there a way to use it?

**Comment by sofisl** [comment]
It seems like minReadySec is only guaranteed in beta: https://cloud.google.com/compute/docs/instance-groups/rolling-out-updates-to-managed-instance-groups#minimum_wait_time

If you think it should be added back, please add a FR to the API directly (search "Compute", you will have the option to list or create a new issue: https://cloud.google.com/support/docs/issue-trackers)

Thank you!
