### ISSUE TITLE
Invalid value for field 'resource.path' when calling invalidateCache

### ISSUE THREAD

**Issue by normand1** [googleapis/google-cloud-node#3667]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-compute/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: `MacOS 12.6`
  - Node.js version: `v18.12.1`
  - npm version: `8.19.2`
  - `@google-cloud/storage` version:  `"@google-cloud/compute": "^3.5.1"`

#### Steps to reproduce

  1. make the following request:
  ```
  const urlMapsClient = new UrlMapsClient({keyFilename: '<project_name>-30d334992f61.json'});

          const invalidateCacheUrlMapRequest = {
            project: '<prpject_name>-290115',
            urlMap: 'http-lb',
            resource: {path: '/images/file.jpg'},
          };
          const response = await urlMapsClient.invalidateCache(invalidateCacheUrlMapRequest);
  ```
  
  2. I receive the following error:
  ```
  [20:38:32.670] ERROR (81169): Invalid value for field 'resource.path': ''. path must begin with /
    err: {
      "type": "GoogleError",
      "message": "Invalid value for field 'resource.path': ''. path must begin with /",
      "stack":
          Error: Invalid value for field 'resource.path': ''. path must begin with /
              at GoogleError.parseHttpError (.../server/node_modules/google-gax/build/src/googleError.js:72:37)
              at decodeResponse (.../server/node_modules/google-gax/build/src/fallbackRest.js:69:49)
              at .../server/node_modules/google-gax/build/src/fallbackServiceStub.js:101:42
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "details": [],
      "code": 3
    }
  ```
I can make the same request in gcloud cli without issue:

```
gcloud compute url-maps invalidate-cdn-cache http-lb \
    --path "/images/file.jpg"
```

Any help would be much appreciated, thank you!

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by zhangjiayin** [comment]
the code should be 

`  const invalidateCacheUrlMapRequest = {
          project: '<prpject_name>-290115',
          urlMap: 'http-lb',
          cacheInvalidationRuleResource: {path: '/images/file.jpg'},
        };
        const response = await urlMapsClient.invalidateCache(invalidateCacheUrlMapRequest);`

**Comment by sofisl** [comment]
Thanks @normand1 for posting this question, and thank you @zhangjiayin for the response! That looks right to me, according to the [sample](https://github.com/googleapis/google-cloud-node/blob/3370cf17724fdf1d233c49cb155db68e26227abf/packages/google-cloud-compute/samples/generated/v1/url_maps.invalidate_cache.js#L56). I'm going to close this for now but feel free to reopen if this doesn't work for you.
