### ISSUE TITLE
[Feature request] Release TTS and STT source code and Google voices as FOSS

### ISSUE THREAD

**Issue by guest271314** [googleapis/google-cloud-node#3674]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to make an external network request for text-to-speech in Chrome when Google voices are used for Web Speech API `speechSynthesis.speak()`. The same is true for `webkitSpeechRecognition()` on Chrome.

For Text-To-Speech Chrome truncates input characters greater than 32768 https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/resources/network_speech_synthesis/tts_extension.js;drc=6c876d3d1412212cd4a671f54aacd9277f985ff2;l=122.

For Speech-To-Text it is not really clear that on Chrome the users' voice is sent to remote servers for processing.

 **Describe the solution you'd like**
Release text-to-speech source code and voices as FOSS (Free Open Source Software)

 **Describe alternatives you've considered**
- Log network activity to analyze the request made by Chrome when Google voices are used with Web Speech API.

- Reverse engineering Native Client .nexe file used for https://chrome.google.com/webstore/detail/us-english-female-text-to/pkidpnnapnfgjhfhkpmjpbckkbaodldb

 **Additional context**
It will be helpful to developers at large and for _accessibility in general_  and _assitive technologies_ for the source code of Google's TTS and STT implementations to be released as open source code.

**Comment by bcoe** [comment]
Hello @guest271314,

Your best bet for a feature request like this would be opening an issue on the appropriate product issue tracker [here](https://cloud.google.com/support/docs/issue-trackers).

This will get you in touch with the product team.
