### ISSUE TITLE
Cannot get Neural2 voices to work. Falls back to WaveNet

### ISSUE THREAD

**Issue by ReeceKenney** [googleapis/google-cloud-node#3723]
Hello,

I'm having difficulty getting neural2 voices to work from my node js application on a raspberry pi. From my research, it seems that neural2 voices are only supported in US Central 1 as documented [here](https://cloud.google.com/text-to-speech/docs/endpoints). I tried running:

`export CLOUD_TTS_ENDPOINT=https://us-central1-texttospeech.googleapis.com`

from the command line assuming that it uses some global value when making the request, but it still always seems to fall back to the wavenet voices.

Is there any way I can specify a region/endpoint with the request? Here's my code in case you need to see it:

```
const request = {
  "audioConfig": {
    "audioEncoding": "LINEAR16",
    "pitch": 0,
    "speakingRate": 1
  },
  "input": {
    "text": "This is the text to be translated"
  },
   "voice": {
    "languageCode": "en-GB",
    "name": "en-GB-Neural2-B"
  }
}
const [response] = await googleClient.synthesizeSpeech(request);
```

Thanks in advance

**Comment by ReeceKenney** [comment]
Okay, it seemed to just eventually work for me. I have no idea what I did, but it now works so I guess setting the region via the command line as mentioned above did in fact work. I can't remember, but I might have just refreshed the environment variables unknowingly. 

My question does still stand though: is there anyway to specify the region/endpoint you want to use when making the request or is setting it via the command line the way I did the recommended approach?

That being said, feel free to close this since it does seem to be working for me!

**Comment by bcoe** [comment]
Hello @ReeceKenney 👋 

You can specify an alternate endpoint using the variable `apiEndpoint` when initializing the client, e.g,.

```js
  // Imports the Google Cloud client library
  const speech = require('@google-cloud/speech');

  // Creates a client
  const client = new speech.SpeechClient({
    apiEndpoint: 'https://us-central1-texttospeech.googleapis.com'
  });
```

Let me know if this does the trick for you.
