### ISSUE TITLE
Dialogflow CX Batch intents update and other operations like in ES sdk

### ISSUE THREAD

**Issue by Mistic92** [googleapis/google-cloud-node#3766]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

There is not option to do operations in batches as it is possible with ES SDK
https://github.com/googleapis/nodejs-dialogflow/blob/main/src/v2/intents_client.ts#L415

Because of that we often have issue with hitting quota limit of 60 requests per minute when doing operations on agent.

There was open issue but closed after migrating to this repo
https://github.com/googleapis/nodejs-dialogflow-cx/issues/247

**Comment by bcoe** [comment]
Hello @Mistic92 👋 

These client libraries are automatically generated from API definitions. For opening a feature request, your best option is to open an issue on the Dialogflow Issue Tracker, listed [here](https://cloud.google.com/support/docs/issue-trackers).
