### ISSUE TITLE
Google Document AI - Impossible to get Long Running Operation's metadata state message

### ISSUE THREAD

**Issue by redvivi** [googleapis/google-cloud-node#3822]
While checking the status of Document AI - Long Running Operation (Form processor), the JSON representation of `decodedOperation.metadata` seems to vary during the execution and accessing `documentai.BatchProcessMetadata.State[decodedOperation.metadata.state]);` returns `TypeError: Cannot read property 'state' of undefined`

This behaviour **does not happen** using similar code for Google Speech's LROs.

Context:
-------------------

At `console.log` line 24 of implemented code (below), *as expected*, `decodedOperation.metadata` resolves to 
```
{
   "state":"RUNNING",
   "createTime":{
      "seconds":"1669278029",
      "nanos":500249000
   },
   "updateTime":{
      "seconds":"1669278029",
      "nanos":500249000
   }
}
```

Current behaviour:
-------------------

At `console.log` line 27, `decodedOperation.metadata.state` returns `2`.
Also `console.log("STATE " + documentai.BatchProcessMetadata.State[decodedOperation.metadata.state]);` returns `TypeError: Cannot read property 'state' of undefined`

Expected behaviour:
-------------------

`decodedOperation.metadata.state` should return `RUNNING`.

More details of output in the code below.

Reproduction details:
-------------------

**Environment:**
`node.js 12.02`

**Package.json:**
```
{
    "dependencies": {
        "@google-cloud/documentai": "latest",
    }
}
```
**Code:**
```
function run() {

    const documentai = require('@google-cloud/documentai').v1;

    // Create a promise on object
    let options = {
        credentials: {
            client_email: ** ** ** ,
            private_key: ** ** * ,
        },
        projectId: ** ** *
    };

    return async (async callback => {

        const client = new documentai.DocumentProcessorServiceClient(options);
        client.checkBatchProcessDocumentsProgress(properties.operation)
            .then(
                (decodedOperation) => {

                    console.log("METADATA " + JSON.stringify(decodedOperation.metadata));
                    /* logs to console:  
                        {
                           "state":"RUNNING",
                           "createTime":{
                              "seconds":"1669278029",
                              "nanos":500249000
                           },
                           "updateTime":{
                              "seconds":"1669278029",
                              "nanos":500249000
                           }
                        }
                    /// then 
                        {
                         "state":"SUCCEEDED",
                         "createTime":{
                            "seconds":"1669278029",
                            "nanos":500249000
                         },
                         "updateTime":{
                            "seconds":"1669278048",
                            "nanos":758825000
                         },
                         "individualProcessStatuses":[
                            {
                               "inputGcsSource":"gs://bucket/intake-form.pdf",
                               "status":{

                               },
                               "outputGcsDestination":"gs://bucket/ocr/7371120297544371692/0",
                               "humanReviewStatus":{
                                  "state":"SKIPPED",
                                  "stateMessage":"HumanReviewConfig is DISABLED, skipping human review."
                               }
                            }
                         ]
                      }
                      */
                    console.log("STATE " + JSON.stringify(decodedOperation.metadata.state));
                    /* log to console: 2 
                     when above is "RUNNING" */

                    /* log to console: 3
                    when above is "SUCCEEDED" */

                    if (decodedOperation.metadata.state == "SUCCEEDED") { // Never triggers as decodedOperation.metadata.state evaluates to an integer at this line

                    };
                    let response = {
                        "operationStatus": decodedOperation.metadata.state
                    };
                    callback(undefined, response);
                })
            .catch(
                (err) => {
                    callback(err);
                });
    })
} 
```    

More details
-------------------------

``util.inspect(decodedOperation.metadata, { showHidden: false })`` returns:

```
BatchProcessMetadata {
   {
      "individualProcessStatuses":[
         "IndividualProcessStatus"{
            "inputGcsSource":"gs://bucketxxx/intake-form.pdf",
            "status":[
               "Status"
            ],
            "outputGcsDestination":"gs://bucketxxx/ocr/7999521463088838887/0",
            "humanReviewStatus":[
               "HumanReviewStatus"
            ]
         }
      ],
      "state":3,
      "createTime":"Timestamp"{
         "seconds":"Long"{
            "low":1670011754,
            "high":0,
            "unsigned":false
         },
         "nanos":105214000
      },
      "updateTime":"Timestamp"{
         "seconds":"Long"{
            "low":1670011773,
            "high":0,
            "unsigned":false
         },
         "nanos":489028000
      }
   }
```

``util.inspect(decodedOperation.metadata, { showHidden: true })`` returns (section of interest only):

`
[...]
[root]: [Getter], [fullName]: [Getter] }, State: { STATE_UNSPECIFIED: 0, WAITING: 1, RUNNING: 2, SUCCEEDED: 3, CANCELLING: 4, CANCELLED: 5, FAILED: 6, '0': 'STATE_UNSPECIFIED', '1': 'WAITING', '2': 'RUNNING', '3': 'SUCCEEDED', '4': 'CANCELLING', '5': 'CANCELLED', '6': 'FAILED' }, encode: <ref *5> [Function: BatchProcessMetadata$encode]
[...]
`

**Comment by sofisl** [comment]
@redvivi, thanks for submitting. Before I look into this deeper, at a cursory glance, it seems like you can avoid needing the response by just awaiting `operation.promise`. See another example [here](https://github.com/googleapis/google-cloud-node/blob/b525661ed04cf91720cf75cb4b0ad0e2ab540ff7/packages/google-cloud-documentai/samples/generated/v1/document_processor_service.batch_process_documents.js#L68).

If you need to poll the exact status of the operation, I'd be tempted to start by looking at the whole operation (instead of just the metadata object), it may be elsewhere.

**Comment by redvivi** [comment]
> Before I look into this deeper, at a cursory glance, it seems like you can avoid needing the response by just awaiting operation.promise.

Unfortunately I am limited in fonction execution duration time. Hence the requirement to poll regularly until success.

**Comment by sofisl** [comment]
Hi @redvivi, it seems like the number that is being returned is an [enum](https://github.com/googleapis/google-cloud-node/blob/def2bc300a3507af7d0250f9ce9b94eaa553d5c7/packages/google-cloud-documentai/protos/google/cloud/documentai/v1/operation_metadata.proto#L30) for the status. What you can do to return the string version is the following:

```
import {protos} from '@google-cloud/documentai';

const client = new DocumentProcessorServiceClient();
const decodedOperation = await.client.checkBatchProcessDocumentsProgress('projects/204535198706/locations/us/operations/3297307537564250929')
const state = protos.google.cloud.documentai.v1.BatchProcessMetadata.State[((decodedOperation.metadata) as any).state]
// Should return "SUCCEEDED"
```

Please let me know if this works for you!

**Comment by sofisl** [comment]
I think each API can implement their metadata [however suits their API](https://cloud.google.com/document-ai/docs/reference/rpc/google.longrunning#operation). In this case, document AI actually recommends using `operation.done` instead of looking at the STATUS object, see their [documentation](https://cloud.google.com/document-ai/docs/long-running-operations#documentai_get_operation-python). It seems that operation.done is common to all APIs, so I might recommend using this instead.
