### ISSUE TITLE
Using ES6 modules

### ISSUE THREAD

**Issue by steren** [googleapis/google-cloud-node#3965]
The docs tell me

```
// Imports the Run library
const {ServicesClient} = require('@google-cloud/run').v2;
```

But my codebase is using ES6 modules.

it's uncler if the `@google-cloud` packages support ES6 modules, or if it's a lack of documentation.

**Comment by sofisl** [comment]
Our client libraries follow Nodejs' active and maintenance [versions](https://github.com/googleapis/google-cloud-node#supported-nodejs-versions); currently we support 12, 14, 16, and 18. To your question, we do support import/export module loading. I also found [this table](https://kangax.github.io/compat-table/es6/) that maps ES versions with Node versions and breaks down compatibility by specific features if you need more detail.

**Comment by steren** [comment]
I just wish the docs had told me modules were supposed and all I had to do was 

```
import * as GoogleCloudRun from '@google-cloud/run';
```

Instead I had to figure this out by myself, including opening this issue because I was in doubt.
