### ISSUE TITLE
Website seems to be from archived repo

### ISSUE THREAD

**Issue by steren** [googleapis/google-cloud-node#3966]
This website https://googleapis.dev/nodejs/run/latest/ points at https://github.com/googleapis/nodejs-run/tree/main/samples which is an archived repository.

**Comment by sofisl** [comment]
Thanks @steren! We've moved over to using cloud.google.com for documentation, which should have the latest info:

https://cloud.google.com/nodejs/docs/reference/run/latest

Would you mind letting us know where you got the link above? We can clean up those links in documentation. Thanks!

**Comment by steren** [comment]
Steps that got me here:

1. https://cloud.google.com/apis/docs/cloud-client-libraries
2. https://cloud.google.com/nodejs/docs/reference
3.  https://googleapis.dev/nodejs/run/latest/

**Comment by steren** [comment]
IMO, the best would be to set up a redirect from the old website to the GitHub sample repo. This would help with SEO and also make sure anyone who linked to the deprecated website would land in the right place.

**Comment by sofisl** [comment]
TODO: fix readme template for APIs.

**Comment by bcoe** [comment]
CC: @dansaadati

**Comment by sofisl** [comment]
So I think this had to do with the docs job not being up to date. I've recently fixed that here: https://github.com/googleapis/google-cloud-node/pull/3982

So for example, even though those docs are out of date, they now should point to the correct links

<img width="1459" alt="Screenshot 2023-02-21 at 1 36 35 PM" src="https://user-images.githubusercontent.com/55454395/220464126-cdcd7e7d-d391-43ed-9d14-790fe3e3977d.png">

Please feel free to open any new issues if you notice broken/missing links. Thanks!
