### ISSUE TITLE
[typeless-sample-bot] Exit code 1 when no TypeScript files found

### ISSUE THREAD

**Issue by kweinmeister** [googleapis/google-cloud-node#4073]
When the `typeless-sample-bot` doesn't find any TypeScript files, it exits with code 1. That will cause builds to fail if `check=True` when running via the synthtool `shell.run()` command.  I do think it's worth flagging as a warning, but I think that only errors in the process should lead to an exit code 1 outcome.

**Comment by feywind** [comment]
Yep, agreed.
