### ISSUE TITLE
This request contains sentences that are too long.

### ISSUE THREAD

**Issue by farraul** [googleapis/google-cloud-node#4074]
I have this problem the library: @google-cloud/text-to-speech

  code: 3,
  details: 'This request contains sentences that are too long.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}

Are there limits to the phrases? I can't find them

**Comment by ddelgrosso1** [comment]
Hi @farraul there is a limit of [5000 bytes per request](https://cloud.google.com/text-to-speech/quotas#content_limits). If your text is very long you may be running into this limitation.

**Comment by agarciar** [comment]
Hi, I just wanted to add a comment regarding the issue we are currently facing with the Text2Speech API. It appears that the API is now rejecting phrases that were previously able to be synthesized without any issues, as was the case in February.

As an example, the following phrase is now being rejected by the API with es-ES-Neural2-F voice:

```text
En la lección encontrarás un video subtítulado de una charla TED de Erez Garty, responsable de comunicación científica del Instituto Davidson de Enseñanza de las Ciencias, explicando cómo distintos tipos de bacterias beneficiosas intervienen, a través de la fermentación, en la producción de distintos alimentos.
```
And this is the error:

```
{
    "message": "This request contains sentences that are too long.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": []
}
```

**Comment by gordon8214** [comment]
This should not have been closed. It’s a different issue than the 5000 byte limit. It seems that in the last couple weeks, the text-to-speech API has instituted a limit to the max length of sentences within the text to to processed. All my existing scripts that have run perfectly for months have started failing. I can’t find any documentation regarding any limit to sentence length. I can’t even find a workaround to this issue as I don’t control the length of sentences in the input data - that’s up to the author. This is a total blocker for my workflows.

**Comment by gordon8214** [comment]
Through trial and error, it appears the limit is 281 characters. Regardless of input length, if there is not a period after every 281 characters, you get an RPC error. I’ve been able to work around this by arbitrarily changing commas to periods in long sentences in my automation, but it’s annoying and results in worse-sounding transcription. Again, this seems new in the last 3 weeks or so and does not appear documented by Google anywhere. Very annoying for a paid service. I had to blow quite a bit of money just figuring out the character limit and working around it.

**Comment by Fleker** [comment]
I ran into this problem today as well when using the neural voice. I had been using a basic voice before which properly abided by the 5000-byte limit without any trouble. But now I'm running into this with a few of my sources. I'm trying to use this API with data I don't directly control. I can try to add periods in lieu of commas, but this "Sentence is too long" error does not provide enough details on the issue to be helpful to the developer in correcting it.

**Comment by gordon8214** [comment]
I'm finding that the previous 281 character limit I found isn't always correct. It's consistent in that going over 281 characters will always trigger the error. However, for reasons I cannot figure out, sometimes much shorter sentences will trigger the same error for no apparent reason. For instance, the following sentence will trigger the error, despite being only 212 characters (with spaces removed, which don't seem to count toward the limit):

> According to a 2020 industry report by Daikoku Denki, total sales of the Japanese pachinko industry shrank from 25.5 trillion yen in 2014 to 14.6 trillion yen in 2021, while gross profits fell from 3.9 trillion yen to 2.4 trillion yen over the same period.

It's impossible to maintain any sort of product that relies on Google text-to-speech when I constantly hit inconsistent, undocumented failures. Can we get some visibility on this?
