### ISSUE TITLE
any example for parameter "parent" in google-cloud-datacatalog-lineage/samples/generated/v1/lineage.search_links.js?

### ISSUE THREAD

**Issue by frandlee** [googleapis/google-cloud-node#4090]
Why was 'abc123'  given as example value for parent?

https://github.com/googleapis/google-cloud-node/blob/46bdeb53e174db4d317d50f88880a78ef1348629/packages/google-cloud-datacatalog-lineage/samples/generated/v1/lineage.search_links.js

many thanks.
 /**
   *  Required. The project and location you want search in.
   */
  // const parent = 'abc123'

**Comment by sofisl** [comment]
Hi @frandlee, this should be fixed by the comments in the protos, since these samples are generated. I've submitted an internal fix for this description: it should be: 

`Required. The project and location you want search in the format `projects/*/locations/*`

cl/517459101 for tracking.

**Comment by sofisl** [comment]
CL submitted, this should be coming through the pipeline soon enough.
