### ISSUE TITLE
Crucial enable/disable functions missing in `@google-cloud/service-management`

### ISSUE THREAD

**Issue by luukvhoudt** [googleapis/google-cloud-node#4097]
In the [readme](https://github.com/googleapis/google-cloud-node/tree/main/packages/google-api-servicemanagement#samples) under the section samples are some functions defined where I was looking for but they don't seem to exist. I didn't check all but I got the following error when calling [`enableService`](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-servicemanagement/samples/generated/v1/service_manager.enable_service.js) or [`disableService`](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-servicemanagement/samples/generated/v1/service_manager.disable_service.js):

```
TypeError: serviceManagementClient.enableService is not a function
```

#### Environment details

  - which product (packages/*): google-api-servicemanagement
  - OS: Ubuntu
  - Node.js version: 18
  - npm version: 9.6
  - google-cloud-node version: 1.2.1?

#### Steps to reproduce

Just try to install one of the following samples:

- [`enableService` sample source code](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-servicemanagement/samples/generated/v1/service_manager.enable_service.js) 
- [`disableService` sample source code](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-servicemanagement/samples/generated/v1/service_manager.disable_service.js)

**Comment by leoortizz** [comment]
just curious.. why this was closed? 

I also tried the sample source code and ended up finding that those methods are not available.

**Comment by luukvhoudt** [comment]
Honestly I can't remember anymore why. I decided to quit using Google after all.

**Comment by leoortizz** [comment]
I see. Can you reopen the issue please?

**Comment by sofisl** [comment]
These functions were removed here, but we didn't remove the samples (apologies): https://github.com/googleapis/google-cloud-node/commit/8325a83d34ee66b66e2f48d72b4a1266509280a1.

I will remove the corresponding samples as well.

Please use these services in the service usage API, i.e.: https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-serviceusage/samples/generated/v1/service_usage.enable_service.js, https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-serviceusage/samples/generated/v1/service_usage.disable_service.js

**Comment by leoortizz** [comment]
> These functions were removed here, but we didn't remove the samples (apologies): [8325a83](https://github.com/googleapis/google-cloud-node/commit/8325a83d34ee66b66e2f48d72b4a1266509280a1).
> 
> I will remove the corresponding samples as well.
> 
> Please use these services in the service usage API, i.e.: https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-serviceusage/samples/generated/v1/service_usage.enable_service.js, https://github.com/googleapis/google-cloud-node/blob/main/packages/google-api-serviceusage/samples/generated/v1/service_usage.disable_service.js

I see, thanks!
