### ISSUE TITLE
RepositoryManagerClient cannot create triggers with a V2 repository

### ISSUE THREAD

**Issue by Parkersungwoo** [googleapis/google-cloud-node#4127]
Hey team,

I'm trying to use the [RepositoryManagerClient](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-devtools-cloudbuild/src/v2/repository_manager_client.ts) to create connections & repositories. When I invoke methods (such as `listConnections()` or `createRepository()` I'm seeing a 500 error
```
HTTP Request Error { status: 500 } Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
code: 13
details: 'Received RST_STREAM with code 2 (Internal server error)',
metadata: Metadata { internalRepr: Map(0) {}, options: {} },
note: 'Exception occurred in retry method that was not classified as transient'
```

This isn't happening with the V1 CloudBuildClient. Any advice would be appreciated. Thanks 🙌🏼

**Comment by sofisl** [comment]
Hi @Parkersungwoo,

I noticed this too, and I think the solution is twofold:

1) I think you need to create these repositories in the v2 client itself (these are separate). So, you'd need to create connections, for example, using [this method](https://cloud.google.com/build/docs/api/reference/rest/v2/projects.locations.connections/create), or in the console.

2) When you create the connections and/or repositories, you'll do so with a region. Make sure to search with this region, and not global, as this will result in that error message as well.

Ultimately, this call worked for me, when using [this sample](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-devtools-cloudbuild/samples/generated/v2/repository_manager.list_connections.js):

```
node repository_manager.list_connections.js projects/<project-name>/locations/us-central1
```

If you confirm this works for you, I can send a note to the API team to update documentation, since it wasn't at all obvious!

**Comment by Parkersungwoo** [comment]
Hey @sofisl thanks for the lead. Taking a closer look at the project path seems to be helpful, although I'm still unable to use these APIs successfully.

I've noticed the REST reference documentation doesn't match the node Protos here. For example, `gitRepoSource` doesn't exist in the Node SDK. [REST reference](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#gitreposource) [Node SDK](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-devtools-cloudbuild/protos/protos.d.ts#L4897)

I'm still working through trying to use this SDK and will report back if/when I'm successful.

**Comment by Parkersungwoo** [comment]
One other thing I noticed in the REST reference docs (feel free to ignore if it's not relevant):
Triggers are described twice. Once [here](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.triggers) and another time [here ](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers)

Additionally, it would be nice if the REST docs described which properties were required/optional.

**Comment by Parkersungwoo** [comment]
My main question would be: How can I use the Node SDK to create a Build Trigger for a 2nd generation Cloud Build repository?

**Comment by gasparev** [comment]
I'm finding an empiric confirmation that the `github` property is v1 specific! If you create a trigger for a v1 repo in the UI this is the payload that it uses:

``` json
{
  "name": "test",
  "description": "",
  "disabled": false,
  "github": {
    "owner": "my-owner",
    "name": "my-repo",
    "push": {
      "branch": "^master$",
      "invertRegex": false
    }
  },
  "autodetect": true
}

```

**Comment by gasparev** [comment]
I found the workaround: using the [Google Cloud Client Library for Node.js](https://github.com/googleapis/google-cloud-node). For future readers, it looks like this:

``` javascript
import { google, cloudbuild_v1, Auth, Common } from 'googleapis';

const projectId = this.projectId;
const parent = `projects/${projectId}/locations/us-central1`;
const trigger = {
    name: `trigger-${triggerParams.triggerName}-pr`,
    disabled: false,
    repositoryEventConfig: {
         pullRequest: {
             invertRegex: false,
             branch: triggerParams.branchPattern,
             commentControl: 'COMMENTS_DISABLED',
         },
         repository: `projects/${projectId}/locations/us-central1/connections/repositoryOwner/repositories/repositoryName`,
    },
    autodetect: true,
    description: ''
};
return await this.cbClient.projects.locations.triggers.create({parent, projectId, requestBody: trigger});

```

**Comment by sofisl** [comment]
Hi @Parkersungwoo and @gasparev, apologies for the delay in responding!

It seems like the V2 surface is still in pre-GA, and therefore does not offer all the same features as the V1 (see the disclaimer [here](https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github?generation=2nd-gen#gcloud). One of which is creating the trigger.

You can use the google-api-nodejs-client library to create the trigger (it uses the [REST interface]([google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client))) until we expose the createTrigger method on the V2 surface.

In the meantime, I've sent over a PR to our docs to update documentation that you need to create V2 resources to use the surface to interact with them.

Please feel free to reopen if this isn't a sufficient response; happy to keep looking into it!
