### ISSUE TITLE
Translation with glossary is not working.

### ISSUE THREAD

**Issue by yatendra121** [googleapis/google-cloud-node#4129]
- which product (packages/*): @google-cloud/translate
  - OS: Windows 11
  - Node.js version: 16
  - npm version: 8.13.1
  - google-cloud-node version: 7.2.0

I am using @google-cloud/translate lib to translate the text using the glossary, but text translation is skipping the glossary words and I have already stored them on the cloud. 

also, I have tried the wrong path of glossary that is throwing an error, which is ok for me.
but I have passed the correct path of glossary that is not throwing any errors also it is not using the glossary words.

I don't understand what I am doing wrong on my side. also, I could not find out a way to figure out the actual issue that is happening. 

The codes are given below:

    const sourceLanguageCode = "en";
    const targetLanguageCode = "zh";
    const text = "this is testing text";
    const glossary = `projects/${projectId}/locations/${location}/glossaries/${glossaryId}`;

    const request = {
      parent: `projects/${projectId}/locations/${location}`,
      contents: [text],
      mimeType: "text/plain",
      sourceLanguageCode,
      targetLanguageCode,
      glossaryConfig: {
        glossary,
      },
    };

    const [response] = await translationClient.translateText(request);

Thank you for your time and consideration.

**Comment by sofisl** [comment]
Hi @yatendra121, could you share your glossary, so that I can reproduce the issue? Also, could you provide testing text that would use the glossary? Thanks in advance.

**Comment by sofisl** [comment]
Going to close this for now, feel free to reopen if you still have this issue!
