### ISSUE TITLE
prediction_service.predict.js  throws errors 13 and 3

### ISSUE THREAD

**Issue by dmitrileroy** [googleapis/google-cloud-node#4131]
prediction_service.predict.js throws error 13 if not passing const clientOptions = {
  apiEndpoint: 'us-central1-aiplatform.googleapis.com',
}; 
to:
new PredictionServiceClient().

After that gives error 3: incorrect instances when instances are array of objects with property content and base-64 encoded string for image.

What works is this https://cloud.google.com/vertex-ai/docs/samples/aiplatform-predict-image-classification-sample
But what is the point of current sample if it's not working? Unless I am missing some step.

**Comment by sofisl** [comment]
@dmitrileroy, it sounds like you're saying that [this sample](https://cloud.google.com/vertex-ai/docs/samples/aiplatform-predict-image-classification-sample) is working for you, but not [this one](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-aiplatform/samples/generated/v1/prediction_service.predict.js)? The former is a handwritten sample, and the latter is autogenerated, so it makes it wouldn't be as robust. In the meantime, I'll take a look to see if there's any way we can add endpoints to autogenerated samples (i.e., if there's a flag to do so).

Another tip, our [quickstarts](https://github.com/googleapis/google-cloud-node/blob/cbd6955a49ea5521bdcf457ccef44008a88eb032/packages/google-cloud-aiplatform/samples/quickstart.js#L30) are also handwritten and tested, so sometimes they help add more depth to the autogenerated samples.

**Comment by sofisl** [comment]
Turns out, we don't have a good flag for indicating if we need to use a different endpoint. As a heads up, we also have handwritten samples [here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/ai-platform/snippets), and we always recommend [using handwritten samples over generated ones](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/ai-platform/snippets)!
