### ISSUE TITLE
Samples links to 404

### ISSUE THREAD

**Issue by skeddles** [googleapis/google-cloud-node#4134]
link on readme for samples is broken

https://github.com/googleapis/nodejs-docs-samples

the one on this page https://www.npmjs.com/package/@google-analytics/data#samples
is as well https://github.com/googleapis/google-cloud-node/tree/main/samples

seems this is the correct link:

https://github.com/googleapis/google-cloud-node/tree/main/packages/google-analytics-data/samples

**Comment by skeddles** [comment]
(also not totally related, but there should be way more examples, the API is extremely confusing to figure out, and the community support forum/discord are dead)

**Comment by sofisl** [comment]
Fixes merged, this is blocked by: https://github.com/googleapis/repo-automation-bots/issues/5024

**Comment by sofisl** [comment]
I think this has been fixed. Please reopen or open a new bug if I missed something. Thank you for reporting!
