### ISSUE TITLE
TextToSpeechLongAudioSynthesizeClient  AudioConfig does not honour `speakingRate` nor any settings

### ISSUE THREAD

**Issue by nickaws** [googleapis/google-cloud-node#4148]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - which product (packages/*):  @google-cloud/text-to-speech"
  - OS: Ventura 13.0.1
  - Node.js version: v19.8.1
  - npm version: 9.5.1
  - google-cloud-node version: 4.2.1

#### Steps to reproduce

  Please include any and all code and/or steps related to reproducing the bug.
```


// Copyright 2023 Google LLC
(from google examples)


'use strict';

function main() {

    const input = { text: "Hey there! I'd be delighted to share with you the latest advancements in car navigation systems. There's so much to talk about, so buckle up and let's get started!" }
    /**
     *  Required. The configuration of the synthesized audio.
     */
    const audioConfig = {
        audioEncoding: "MP3",
        speakingRate: "0.5"
    }
    /**
     *  Specifies a Cloud Storage URI for the synthesis results. Must be
     *  specified in the format: `gs://bucket_name/object_name`, and the bucket
     *  must already exist.
     */
    // const outputGcsUri = 'abc123'
    /**
     *  The desired voice of the synthesized audio.
     */
    const voice = {
        name: "en-US-Wavenet-J",
        languageCode: 'en-US'
    }

    // Imports the Texttospeech library
    const { TextToSpeechLongAudioSynthesizeClient } = require('@google-cloud/text-to-speech').v1;

    // Instantiates a client
    const texttospeechClient = new TextToSpeechLongAudioSynthesizeClient();

    async function callSynthesizeLongAudio() {
        // Construct request
        const request = {
            voice,
            input,
            audioConfig,
            outputGcsUri: "gs://somebucket/file.mp3"
        };

        // Run request
        const [operation] = await texttospeechClient.synthesizeLongAudio(request);
        const [response] = await operation.promise();
        console.log(response);
    }

    callSynthesizeLongAudio();
}

process.on('unhandledRejection', err => {
    console.error(err.message);
    process.exitCode = 1;
});
main();
```

Speaking rate nor pitch are honoured.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by danielbankhead** [comment]
Hey @nickaws,

`speakingRate` and `pitch` should be `number`s, not `string`s:

https://github.com/googleapis/google-cloud-node/blob/94ea195acc92d947f27374a5a8c753c2f0cc1d0e/packages/google-cloud-texttospeech/protos/protos.d.ts#L786-L790

**Comment by nickaws** [comment]
Hi @danielbankhead ! this actually made no difference, and even throws "'Request contains an invalid argument.'," with the code above (which worked sometimes)

**Comment by danielbankhead** [comment]
@nickaws to clarify, the request should look like this:

```ts
const operation = await texttospeechClient.synthesizeLongAudio({
  voice: {
    name: "en-US-Wavenet-J",
    languageCode: 'en-US'
  },
  input,
  audioConfig: {
    audioEncoding: "MP3",
    speakingRate: 0.5,
    // pitch: 1,
  },
  outputGcsUri: "gs://somebucket/file.mp3"
});
```

Does this request not work for you?

> which worked sometimes

I'm not sure how a request parameter would fail sometimes; are there any additional details here?

**Comment by nickyamanaka** [comment]
@danielbankhead  I am very sorry for the cryptic message.

The code I put when I opened the ticket, generated an mp3 but crashed with "Request contains an invalid argument.'" right now, the same code, with the new request works sometimes (it does generate the mp3), sometimes fails with  -- using latest sdk.
```
[
  {
    voice: { name: 'en-US-Wavenet-J', languageCode: 'en-US' },
    input: {
      text: "Hey there! I'd be delighted to share with you the latest advancements in car navigation systems. There's so much to talk about, so buckle up and let's get started!"
    },
    audioConfig: { audioEncoding: 'MP3', speakingRate: 0.5 },
    outputGcsUri: 'gs://xxx/file2.mp3'
  },
  Metadata {
    internalRepr: Map(2) {
      'x-goog-api-client' => [Array],
      'x-goog-request-params' => [Array]
    },
    options: {}
  },
  { deadline: 2023-04-10T19:06:05.200Z },
  [Function (anonymous)]
]
3 INVALID_ARGUMENT: Request contains an invalid argument.
```
