### ISSUE TITLE
[typeless-sample-bot] Don't return error when no samples are selected

### ISSUE THREAD

**Issue by kweinmeister** [googleapis/google-cloud-node#4209]
When running the `typeless-sample-bot`, it returns a non-zero exit code when no samples are found. There are situations in which we we are running the bot against samples in an unknown state, and it's OK if there are no samples.

Returning an error both when there are real errors and no selected samples means it's difficult to pinpoint when there are real issues, or more complex pre-processing logic is needed to avoid this.

Note the comment in the code :)
```
if (!count) {
      // Should this be considred a failure?
      loggers.error('No samples were selected.');
    }
```

Example error log:
```
023-04-25 12:25:52,138 synthtool [ERROR] > Failed executing /synthtool/node_modules/.bin/typeless-sample-bot --targets /workspace/nodejs-docs-samples/appengine/typescript --recursive:

Typeless sample bot, converts TS to JS sample snippets
❌ No samples were selected.
❌ Something failed. (Maybe not everything, check the log above.)

Traceback (most recent call last):
  File "/workspace/nodejs-docs-samples/owlbot.py", line 173, in <module>
    f = typeless_samples_hermetic(targets=d)
```

**Comment by bcoe** [comment]
I think this should be fixed now: https://github.com/googleapis/google-cloud-node/issues/4073
