### ISSUE TITLE
getting metadata from plugin failed with error: key must be a string, a buffer or an object dialogflow client

### ISSUE THREAD

**Issue by ujikstark** [googleapis/google-cloud-node#4327]
i got an error getting metadata from plugin failed with error: key must be a string, a buffer or an object dialogflow client when i'm try in hosting. when i'm try in localhost its work without error like that.

**Comment by ujikstark** [comment]
solved with saved the private_key in .env

**Comment by YakovL** [comment]
@ujikstark how do you apply `private_key` in this case? I have this issue with Firestore and I'm doing

const db = new Firestore({
    projectId: 'somename',
    keyFilename: './firebase-calmflow.json',
});

so not sure where to put `private_key` if I load it from ENV.

**Comment by YakovL** [comment]
A general suggestion for others having this issue: check your credentials JSON. In my case, wrong CD removed all " chars from it, hence wrong parsing occured.
