### ISSUE TITLE
Compatibility issue with glob and rimraf package

### ISSUE THREAD

**Issue by vijaypd7** [googleapis/google-cloud-node#4451]
I am trying to integrate google analytics data client _"@google-analytics/data": "^3.3.0"_ in my nestJS project.
My node version is `v16.17.0` and npm version `8.15.0`.

I have a dependency with the npm package _"glob": "^10.3.3"_.

So when I add @google-analytics/data package in project and then try to start the app. It is throwing an error like this:
```

node_modules/@types/rimraf/index.d.ts:33:21 - error TS2694: Namespace '"/home/Desktop/project/node_modules/glob/dist/mjs/index"' has no exported member 'IOptions'.

33         glob?: glob.IOptions | false | undefined;
                       ~~~~~~~~

node_modules/glob/node_modules/minipass/dist/cjs/index.d.ts:5:30 - error TS2307: Cannot find module 'node:events' or its corresponding type declarations.

5 import { EventEmitter } from 'node:events';
                               ~~~~~~~~~~~~~

node_modules/glob/node_modules/minipass/dist/cjs/index.d.ts:6:31 - error TS2307: Cannot find module 'node:string_decoder' or its corresponding type declarations.

6 import { StringDecoder } from 'node:string_decoder';
```
Removing the glob package seems to fix the issue. Suspect this is a compatibility issue.

**Comment by sambauers** [comment]
Looks like this is buried in another dependency https://github.com/googleapis/gax-nodejs/issues/1463 

No idea when that fix will be released though.
