### ISSUE TITLE
Google Cloud Domains Missing API Calls

### ISSUE THREAD

**Issue by samishal1998** [googleapis/google-cloud-node#4624]
Some essential operations are missing from this library "@google-cloud/domains" 
|Operation|
|-|
| [retrieveImportableDomains](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/retrieveImportableDomains)|
|[import](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/import)|
|[get](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/get)|
|[getIamPolicy](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/getIamPolicy)|
|[setIamPolicy](https://cloud.google.com/domains/docs/reference/rest/v1/projects.locations.registrations/setIamPolicy)|

**Comment by sofisl** [comment]
Sorry for the delay - these have been deprecated.
