### ISSUE TITLE
how do i import the types?

### ISSUE THREAD

**Issue by leandroruel** [googleapis/google-cloud-node#4653]
i`m trying to import the types of some class here but i can't.. example:

`import { ISearchRequest } from '@google-cloud/retail'`

**Comment by ddelgrosso1** [comment]
The interface `ISearchRequest` is not exported. However, you can get access to the implementation type `SearchRequest`.

```
import { protos } from "@google-cloud/retail";
const sr: protos.google.cloud.retail.v2.SearchRequest = ...
```
