### ISSUE TITLE
SQL: 13 INTERNAL: Received RST_STREAM with code 0

### ISSUE THREAD

**Issue by folkg** [googleapis/google-cloud-node#4679]
**Environment details**
    which product (packages/*): @google-cloud/sql": "^0.1.0"
    OS: MacOS Ventura 13.4.1
    Node.js version: v20.4
    npm version: 9.7.2

**Steps to reproduce**

I get the following error message:
`13 INTERNAL: Received RST_STREAM with code 0`

Using the following code:

```
import { SqlDatabasesServiceClient } from "@google-cloud/sql";

const sqlClient = new SqlDatabasesServiceClient();
const [databases] = await sqlClient.list({
  instance: INSTANCE,
  project: PROJECT_ID,
});
```

**Comment by sofisl** [comment]
Hi @folkg, thanks for reporting. This API is new and  a bit of a strange case, you need to pass in `fallback: rest` (like [so](https://github.com/googleapis/google-cloud-node/blob/606e6e5a290b71494c74df1ca84d5227d72190cc/packages/google-cloud-sql/samples/quickstart.js#L27-L29)) when initializing the client to get it to work properly. In the meantime we'll work on a default more permanent fix.

Thanks!
