### ISSUE TITLE
monitoring: listAlertPolicies does not return policy.alertStrategy

### ISSUE THREAD

**Issue by sourceful-alex** [googleapis/google-cloud-node#4686]
The response from alertPolicyServiceClient.listAlertPolicies() does not include policy.alertStrategy.

alertStrategy is inlcuded in the API documentation https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#alertstrategy

I have verified that alertStrategy is included in the response when I manually make an API call. The policy in question has an alertStrategy set, with the autoClose value changed from the default.

#### Environment details

  - which product (packages/*):  @google-cloud/monitoring version 4.0.0
  - OS: Kubuntu 23.04
  - Node.js version: v17.9.1
  - npm version: 8.11.0

#### Steps to reproduce

`npm install --save @google-cloud/monitoring typescript ts-node`

```
import { Monitoring } from '@google-cloud/monitoring';

const projectId = 'YOUR_GCP_PROJECT_ID';  // Replace with your GCP Project ID

// Initialize the Google Cloud Monitoring client
const monitoring = new Monitoring({
  projectId,
});

// Function to export alert policies
async function exportAlertPolicies() {
  const alertPolicyServiceClient = monitoring.alertPolicyServiceClient();
  const [alertPolicies] = await alertPolicyServiceClient.listAlertPolicies({
    name: `projects/${projectId}`,
  });

  return alertPolicies;
}
```

**Comment by sofisl** [comment]
Hi @sourceful-alex,

The documentation you're referencing is exposing the REST API, whereas this library is autogenerated code from grpc. Likely, this property hasn't been exposed (you can look through [here](https://github.com/googleapis/google-cloud-node/blob/19db820e5b164932f27fb740382294efdb7d5005/packages/google-cloud-monitoring/protos/protos.d.ts#L1851), where alertStrategy is missing, and which is what we use to autogenerate the libraries). The REST API client library is [here](https://github.com/googleapis/google-api-nodejs-client/tree/main#http2), and it seems like it does expose the [alertStrategy](https://github.com/googleapis/google-api-nodejs-client/blob/84d2d60ea1d733d889147b9ef4130ad4a1ea913a/src/apis/monitoring/v3.ts#L163) property. You can use this [submodule](https://www.npmjs.com/package/@googleapis/monitoring) to directly interact with the monitoring REST API.
