### ISSUE TITLE
[Retail API] SearchServiceClient can't use pageSize for pagination

### ISSUE THREAD

**Issue by suckseedrom** [googleapis/google-cloud-node#4691]
Hi All,

Now, I use SearchServiceClient.search with pageSize but the result don't match with pageSize and don't return next page token 

Environment:
Node version: v18.17.1 "@google-cloud/retail": "^3.0.0"
Here's An example object in the array from client.search:

#### Steps to reproduce

I call this function with pageSize = 10;

```
 const placement = `projects/${process.env.GCP_PROJECT_ID}/locations/global/catalogs/default_catalog/placements/default_search`;
    const visitorId = searchDto.visitorId || "1";
    const query = searchDto.query
    const pageSize = searchDto.pageSize;
    const pageToken = searchDto.pageToken;
    const filter = searchDto.filter;
    const offset = searchDto.offset;

    const searchRequest = {
      placement,
      visitorId,
      query,
      filter,
      pageToken,
      pageSize,
      offset
    };
    const response = await this.searchClient.search(searchRequest, {})
```

but result is get more 100 products
Thanks!

**Comment by sofisl** [comment]
Could you try setting `{autoPaginate: false}` when you initialize the client?

**Comment by suckseedrom** [comment]
> Could you try setting `{autoPaginate: false}` when you initialize the client?

It is work. but I want to get next page token but the result don't return that. How I should do ?

**Comment by suckseedrom** [comment]
> Could you try setting `{autoPaginate: false}` when you initialize the client?

It's work. Thanks you :)
