### ISSUE TITLE
Talent: custom attributes error "Starting an object on a scalar field" when using fallback mode

### ISSUE THREAD

**Issue by dimip1606** [googleapis/google-cloud-node#4743]
#### Environment details

  - @google-cloud/talent 6.0.1
  - OS: macOS Ventura 13.5.2
  - Node.js version: 18

#### Steps to reproduce

Consider the following snippet:
```js
import { v4 } from '@google-cloud/talent'

const client = new v4.JobServiceClient({ fallback: true })
const [operation] = await client.batchCreateJobs({
  parent: 'your-tenant-path',
  jobs: [
    {
      // <your other job data>
      customAttributes: {
        testAttribute: { longValues: [1], filterable: true },
      },
    },
  ],
})

const [response] = await operation.promise()
```

Executing it will result in the following error:

_Invalid value at 'jobs[0].custom_attributes[0].value.long_values' (long_values), Starting an object on a scalar field
at GoogleError.parseHttpError (/usr/src/app/node_modules/google-gax/build/src/googleError.js:72:37)
   at decodeResponse (/usr/src/app/node_modules/google-gax/build/src/fallbackRest.js:66:49)
   at /usr/src/app/node_modules/google-gax/build/src/fallbackServiceStub.js:104:42
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)_

This only happens when using fallback mode.

When digging deeper, you will find out that in [fallbackRest.ts (google-gax)](https://github.com/googleapis/gax-nodejs/blob/34a6d6021d2f2f53ceab3b76ef2ceccb5a3f2013/gax/src/fallbackRest.ts#L36), the `fromObject()` method will transform the longValues of a custom attribute into a `Long` object: `longValues: [ Long { low: 1, high: 0, unsigned: false } ]`.
This is most likely wrong, because according to the REST API of Cloud Talent Solutions, the value inside a `longValues` array must be of type number/string (see [here](https://cloud.google.com/talent-solution/job-search/docs/reference/rest/v4/projects.tenants.jobs#CustomAttribute.FIELDS.long_values)).

**Comment by sofisl** [comment]
@alexander-fenster FYI

**Comment by mctrafik** [comment]
Hi, I see this as completed, but when is this going to fix the issues in @google-cloud/monitoring package? I see google-gax was updated, but the issue still persists.

**Comment by sofisl** [comment]
I don't think this works with http. Can you try the following:

```
rm -rf node_modules && rm -rf package-lock.json
npm i

//code snippet
const client = new v4.JobServiceClient() // remove fallback
```

**Comment by mctrafik** [comment]
I don't know what you mean. My comment was about the fact that downstream libraries need to be updated to include this.

This PR is in `proto3-json-serializer-nodejs@2.0.2` but `google-gax` doesn't require it at that version: https://github.com/googleapis/gax-nodejs/blob/a7a233aa5a3ffb4da9dd7fc55ab92afc370730e0/gax/package.json#L21

And when google-gax is updated, all the @google-cloud/* packages needed to be updateed as well. Only then devs can benefit from this bugfix.

**Comment by sofisl** [comment]
google-gax will grab the latest version, and so will all the google-cloud packages. You just need to make sure to remove any cached node modules and reinstall your package-lock so that it grabs the most recent version of proto3-json-serializer.

**Comment by mctrafik** [comment]
It has been a month. So it's not an automated process to grab the latest version unless I'm missing something. In the file I linked the job has kept the dep 2.0.0 instead of upgrading. Can you elaborate on what the intended process is?

**Comment by mctrafik** [comment]
That isn't something that you can ask devs to do! I think there's a
misconception here that it's always safe to run `npm upgrade` or reinstall
package lock from scratch. That isn't the case. There are MANY packages
that have breaking changes and only bump minor versions. In repos with
millions of lines of code that introduces a huge undue burden. On teams in
my company package upgrades happen every 1-2 year and require 1-2 weeks of
effort! The upgrade path has to include a basic version bump, i.e. `npm
install @***@***.***` and that's it!!!
