### ISSUE TITLE
__dirname is not defined when trying to create assessment

### ISSUE THREAD

**Issue by wojtekmaj** [googleapis/google-cloud-node#4763]
#### Environment details

  - which product (packages/*): @google-cloud/recaptcha-enterprise 4.1.0
  - OS: macOS
  - Node.js version: 20.9.0
  - npm version: 10.0.0
  - google-cloud-node version: ?

#### Steps to reproduce

Create Node.js ESM application.
Create assessment as instructed in documentation.
Build the app with ESBuild (probably irrelevant, because related directly to __dirname not defined in ESM environment, but mentioning it for completeness)

This causes the following error:

```
Exception: __dirname is not defined
Stack: ReferenceError: __dirname is not defined
    at ../node_modules/google-gax/build/src/grpc.js (/dist/submit/index.js:60459:41)
    at __require2 (/dist/submit/index.js:17:51)
    at ../node_modules/google-gax/build/src/index.js (/dist/submit/index.js:80590:18)
    at __require2 (/dist/submit/index.js:17:51)
    at new RecaptchaEnterpriseServiceClient2 (/dist/submit/index.js:80793:25)
    at createAssessment (/dist/submit/index.js:112803:22)
```

**Comment by wojtekmaj** [comment]
A workaround just to get going further would be to add use Esbuild's `banner.js` setting to inject `const __dirname = new URL('.', import.meta.url).pathname;`.

**Comment by ddelgrosso1** [comment]
Hi @wojtekmaj currently these libraries are written to support `CJS`. As you noted `__dirname` is not available in `ESM`. While we are currently investigating the possibility of supplying `ESM` alongside `CJS` there is no concrete time frame. My suggestion if you are using `esbuild` is to look for a plugin out there that can help replace instances of `__dirname`.

**Comment by wojtekmaj** [comment]
It looks like after adding this workaround it works just fine. A low hanging fruit to fix? 🧐

**Comment by ddelgrosso1** [comment]
@wojtekmaj I'm not sure I understand what you mean by a low hanging fruit to fix? Do you mean swap out `__dirname` for the code you mentioned above?

**Comment by wojtekmaj** [comment]
What I mean is that it seems __dirname is the only thing breaking ESM compatibility, so just replacing this bit with something else would make it far easier for ESM folks :)

BTW, ESM as default is now an experimental flag in Node.js 21, so I expect somewhere around Node.js 24 far more people will be hitting this.

**Comment by ddelgrosso1** [comment]
WAI for the time being since ESM support has not been introduced to these libraries. Going to close this out.
