### ISSUE TITLE
Higher-Level VertexAI APIs for NodeJS

### ISSUE THREAD

**Issue by abegehr** [googleapis/google-cloud-node#4792]
It would be neat to get some higher-level APIs to work with like TextGenerationModel in Python: https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.language_models.TextGenerationModel

Currently I'm working with PredictionServiceClient directly:
https://github.com/googleapis/google-cloud-node/blob/489e188d97af302f96299a5b40eb5e07020972fc/packages/google-cloud-aiplatform/samples/generated/v1/prediction_service.predict.js#L72

**Comment by abegehr** [comment]
I'm not fully sure but I think this might be what I'm looking for: https://github.com/googleapis/google-cloud-node/tree/main/packages/google-ai-generativelanguage

**Comment by abegehr** [comment]
Hm, it seems that `@google-ai/generativelanguage` is using the GCP's Generative Language API, whereas I was looking to use the Vertex AI API. Not sure if they're the same.
My original attempt was to execute this Vertex AI prompt sample from NodeJS: https://console.cloud.google.com/vertex-ai/generative/language/prompt-examples/Hashtag%20tokenization. It's not clear which package and service to use for this from NodeJS.

**Comment by diegomansua** [comment]
@abegehr did you manage to use the `@google-ai/generativelanguage` package with Vertex API?
