### ISSUE TITLE
Bug in Search & Conversation node.js API: cannot create datastore

### ISSUE THREAD

**Issue by edudesouza** [googleapis/google-cloud-node#4845]
#### Environment details

  - which product (packages/*): 
  - OS: Google Cloud Functions
  - Node.js version: Node 18.15.0
  - npm version:  9.5.0
  - google-cloud-node version: ???

#### Steps to reproduce

Hi there, following this doc:

https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-discoveryengine/samples/generated/v1alpha/data_store_service.create_data_store.js

I cannot create a DataSotre, but the interesting part is ... the error log points to another project ID, error message:

7 PERMISSION_DENIED: Discovery Engine API has not been used in project **563584335869** before or it is disabled. Enable it by visiting [https://console.developers.google.com/apis/api/discoveryengine.googleapis.com/overview?project=56358...](https://console.developers.google.com/apis/api/discoveryengine.googleapis.com/overview?project=**563584335869**) then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**This project 563584335869 is not mine** ... code print below, this I mentined above,  was publushed last week, so I think there is a bug in the API some 'hard code' somewhere.

![image](https://github.com/googleapis/google-cloud-node/assets/177087/0797f060-e7ae-45df-8eb6-21daf1a0da1e)

**Comment by sofisl** [comment]
Hi @edudesouza, I think this is a bug with the error reporting. 

Can you confirm what login you have with application default credentials? Please run `gcloud auth application-default login` in your terminal to login with the correct account.

**Comment by edudesouza** [comment]
OK, did that, and same error, prints below
![image](https://github.com/googleapis/google-cloud-node/assets/177087/93b96a23-5f4f-4420-b693-39540aa2ebdd)

Started Firebase emulator:
![image](https://github.com/googleapis/google-cloud-node/assets/177087/29a38a5b-e865-4d62-84bd-139c6270d712)

Got same error
![image](https://github.com/googleapis/google-cloud-node/assets/177087/a5af13e0-750f-49f4-b3fd-3478ee432afe)

**Comment by sofisl** [comment]
I think this might have to do with your emulator.

To test, can you try running the code directly (without the emulator)? You can do so just by running the sample directly, i.e., `node samples/generated/v1alpha/data_store_service.list_data_stores.js` (make sure to run `npm link ../` from the samples directory beforehand). 

If it works (or gives you a different authentication error), I'd be willing to bet there's an additional authentication step you need to do with the emulator.

**Comment by sofisl** [comment]
Closing for now due to inactivity; feel free to reopen if you want to keep investigating!

**Comment by edudesouza** [comment]
Hi there, sorry about my late response.
I found the problem / solution.

I have 2 environmets in my cloud function, in production I have de declare wich one I am using.
