### ISSUE TITLE
Using @google-cloud API's in preview after being granted access

### ISSUE THREAD

**Issue by igloo1505** [googleapis/google-cloud-node#4850]
I apologize if this issue is covered somewhere. I assume it is, but I've looked and looked and haven't had any luck finding an answer. I'm trying to access Google's new Meet API. I followed the process in the docs to get preview access, and received an email alerting me that our organization was approved. The Google Meet API became available in the API library section of the cloud console, and I was able to enable it without any issue, but my question is this:

If the `@google-cloud/meet` package isn't available in NPM, where can I find it to actually work with the API? All of the existing docs on this API use this package, and I've checked for any repos that might need to be cloned, but so far I've had no luck actually finding that package anywhere.

Any help would be hugely appreciated. Thanks in advance.

**Comment by sofisl** [comment]
Thanks for posting the question! Not obvious at all! The library is in preview, so it's actually only being shared in this google drive: https://drive.google.com/corp/drive/folders/123-HbZc3XEZeELXkyl2OkEhGoEf0q-tc. I've asked the owner of the drive to share it with your email address attached to this github account. Please feel free to post if this doesn't work!
