### ISSUE TITLE
Error after Updating `@google-cloud/tasks` to ^4.1.0: Firestore Snapshot Decoding Issue

### ISSUE THREAD

**Issue by masanori-iwata** [googleapis/google-cloud-node#4857]
Thanks for stopping by to let us know something could be better!

**Issue Description:**
After updating `@google-cloud/tasks` from version ^3.1.2 to ^4.1.0, I encountered a runtime error in my Firebase function. The issue seems to be related to decoding Firestore snapshots. The error message is as follows:
#### Environment details

  - Product: `@google-cloud/tasks`
  - OS: macOS Sonoma 14.1.2 (Chip Apple M1 Pro, Memory 16GB, Startup Disk Macintosh HD)
  - Node.js version: v18.7.0
  - npm version: v10.2.4
  - `google-cloud-node` dependencies:
    - `@google-cloud/firestore`: ^7.1.0
    - `@google-cloud/pubsub`: ^4.0.7
    - `@google-cloud/secret-manager`: ^5.0.1
    - `@google-cloud/storage`: ^7.7.0
    - `@google-cloud/tasks`: ^4.1.0
    - `@googlemaps/google-maps-services-js`: ^3.3.41
    - `firebase-admin`: ^11.11.1
    - `firebase-functions`: ^4.5.0

#### Steps to reproduce

  1. Update `@google-cloud/tasks` from ^3.1.2 to ^4.1.0.
  2. Execute the Firebase function which interacts with Firestore.
  3. Observe the error in the function logs.

I have already checked the open issues, StackOverflow, the troubleshooting guide, and the FAQ but didn't find a similar issue or solution. Any assistance or guidance would be greatly appreciated.

Thanks!

**Comment by Xennis** [comment]
Not sure if it's related (because the error message seems to be missing here) but I ran with the new version 4.1.0 into #4858

**Comment by sofisl** [comment]
Could I trouble you for the code that failed? Thank you in advance.
