### ISSUE TITLE
Unable to import `@google-cloud/tasks` after update to v4.1.0

### ISSUE THREAD

**Issue by sambauers** [googleapis/google-cloud-node#4859]
After updating `@google-cloud/tasks` from `4.0.1` to `4.1.0` a basic `import` of the package fails.

When importing using:

```ts
import { CloudTasksClient } from '@google-cloud/tasks'
```

We receive this error on project `build` (we build using simple `tsc` command):

> The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@google-cloud/tasks")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '<redacted-path>/package.json'.ts(1479)
module "<redacted-path>/node_modules/@google-cloud/tasks/build/cjs/src/index"

#### Environment details

  - which product (packages/*): `@google-cloud/tasks`
  - OS: `Mac OS X`
  - Node.js version: `18.18.0`
  - npm version: `yarn 1.22.19`
  - google-cloud-node version: `4.1.0`
  - Typescript version: `5.3.2`

#### Steps to reproduce

`package.json`

```json
{
  "name": "my-project",
  "private": true,
  "dependencies": {
    "@google-cloud/tasks": "4.1.0"
  },
  "devDependencies": {
    "@tsconfig/node18": "18.2.2",
    "@types/node": "18.18.6",
    "@typescript-eslint/eslint-plugin": "6.13.1",
    "@typescript-eslint/parser": "6.13.1",
    "eslint": "8.54.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-plugin-import": "2.29.0",
    "eslint-plugin-jest": "27.6.0",
    "eslint-plugin-prettier": "5.0.1",
    "eslint-plugin-simple-import-sort": "10.0.0",
    "nodemon": "3.0.1",
    "prettier": "3.1.0",
    "ts-node": "10.9.1",
    "typescript": "5.3.2"
  },
  "scripts": {
    "lint": "eslint 'src/**/*.{ts,tsx}' --cache",
    "build": "tsc"
  }
}
```

`tsconfig.json`

```json
{
  "extends": "@tsconfig/node18",
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "outDir": "build",
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

`src/tasks.ts`

```ts
import { CloudTasksClient } from '@google-cloud/tasks'
```

**Comment by sambauers** [comment]
This issue is a bit more fundamental, but it is probably related to #4857 and #4858.

**Comment by sofisl** [comment]
As a workaround, I've republished the 'latest' tag as 4.0.1. This should have been released as a breaking change. Please re-install the package at latest, it should work.

**Comment by sofisl** [comment]
Could I trouble you for the code that failed? Thank you in advance.

**Comment by AntQwanlity** [comment]
Having this issue after migration to 5.0

**Comment by kirillgroshkov** [comment]
Same

**Comment by jordanebelanger** [comment]
Same

**Comment by sambauers** [comment]
> Could I trouble you for the code that failed? Thank you in advance.

The only relevant code is the import line. That's all it takes to trigger the error:

```ts
import { CloudTasksClient } from '@google-cloud/tasks'
```

**Comment by dipbhi** [comment]
#5683

**Comment by dipbhi** [comment]
#5683
