### ISSUE TITLE
Analytics Data API: What IAM roles or permissions are required?

### ISSUE THREAD

**Issue by dpkirchner** [googleapis/google-cloud-node#4901]
Per the README we are supposed to create a service account to access Google Analytics data. What IAM roles or permissions do we need to assign to that service account? Otherwise, how do we grant access to GA to that service account? The README just links to generic service account docs.

**Comment by sofisl** [comment]
From what I understand, you don't need to give the SA any special permissions, but you do need to add it onto your account using its email address: (see https://support.google.com/analytics/answer/1009702?hl=en#zippy=%2Cin-this-article)

@ikuleshov, would you mind confirming?

**Comment by ikuleshov** [comment]
As per the [quickstart guide](https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries#step_2_add_service_account_to_the_google_analytics_4_property), a Service Account needs to be added to the Google Analytics account/property you are trying to access, no other IAM roles needed.
