### ISSUE TITLE
The attribute `includeBuildLogs` is missing in Cloud Build triggers

### ISSUE THREAD

**Issue by christian-roggia** [googleapis/google-cloud-node#5103]
Affected package: `google-devtools-cloudbuild`

The attribute `includeBuildLogs` is missing from both the proto definitions and the client library implementation.

See https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger.IncludeBuildLogs

**Comment by sofisl** [comment]
Unfortunately this is not available yet for grpc transport, only in rest. You can use this feature in the REST transport library: https://github.com/googleapis/google-api-nodejs-client/blob/2db4c4dcb90f0a9b5564c0ae122312bd6f82809b/src/apis/cloudbuild/v1.ts#L813
