### ISSUE TITLE
Documentation links in @googlemaps/places don't work

### ISSUE THREAD

**Issue by RobertPietraru** [googleapis/google-cloud-node#5272]
In short: API reference link at [npm page](https://www.npmjs.com/package/@googlemaps/places) doesn't work.

#### Environment details
- Any browser, from Romania (in case it's not available in my country)

#### Steps to reproduce
- Go to https://www.npmjs.com/package/@googlemaps/places 
- Go to the readme section
- Tap on [Places API (New) Node.js Client API Reference](https://cloud.google.com/nodejs/docs/reference/places/latest)

This will take you to https://cloud.google.com/nodejs/docs/reference/places/latest, returning a 404

Also applies to [Places API (New) Node.js Client API Reference](https://cloud.google.com/nodejs/docs/reference/places/latest)

Just to be clear, I'm talking about these links:
![image](https://github.com/googleapis/google-cloud-node/assets/64798198/4b52d41a-de52-49fe-a200-126bf250c820)
![image](https://github.com/googleapis/google-cloud-node/assets/64798198/0b29ea87-c340-488a-a974-fe3ef1748e27)

**Comment by sofisl** [comment]
cc @dansaadati, were you ever able to look into this bug with publication?

**Comment by dansaadati** [comment]
> cc @dansaadati, were you ever able to look into this bug with publication?

Yes -- the PR for the docs issue for non-Cloud namespaces is here: https://github.com/googleapis/nodejs-cloud-rad/pull/108
