### ISSUE TITLE
Breaking change in minor release of @google-cloud/secret-manager 5.4.0

### ISSUE THREAD

**Issue by mnahkies** [googleapis/google-cloud-node#5289]
A method was renamed by https://github.com/googleapis/google-cloud-node/pull/5273/files#diff-58dd618354fa97803f0fa5355182bc50d81235cca30945857c179071555ebfd1L2213-R2343 in a backwards incompatible way.

#### Environment details
  - which product (packages/*): `@google-cloud/secret-manager`
  - google-cloud-node version: 5.4.0

#### Steps to reproduce
Public method  `secretVersionPath` was renamed to `projectLocationSecretSecretVersionPath` in a minor release.

Ideally the previous name would be kept for backwards compatibility.

**Comment by mattkindy** [comment]
Having this issue as well
```typescript
TypeError: client.secretVersionPath is not a function
```

**Comment by sofisl** [comment]
Looking!
