### ISSUE TITLE
What should the story be for a client-side Javascript gcloud library?

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-node#531]
If we were to try building a gcloud library that was usable from the browser, how would we go about that?

**Comment by ryanseys** [comment]
It all comes down to dependencies. We can potentially use browserify to a certain degree but I know we'd hit hard issues with `fs` (file system access) which means that everything from file uploads to reading our credentials from a json file are pretty much kaput. Hard to say what good work-arounds would be for that. Obviously Google makes use of it front-end already using the Google Developer's Console, but how they are accomplishing that I'm not too certain.

**Comment by jgeewax** [comment]
The ultimate goal is to provide an in-browser client library that someone building their own copy of the Developer's Console could use, and ideally we could find a way to share lots of code.

Regarding file system access for file uploads: we'd have to ask how that's being done today. Clearly there is a way to upload files in a browser...

Regarding file system access for auth: I suspect we'd end up relying on 3-legged authentication to make this all work.

Some other questions:

- Are there other libraries out there that work both in the Node runtime as well as in the browser?
- Is there any way to share some of the code between the two libraries and then have the run-time specific parts isolated ?
- Is it reasonable to go down this route? or should we just consider doing `gcloud-javascript` which would be an in-browser JS library to talk to cloud services?

**Comment by ryanseys** [comment]
Getting files is done with the [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) from either a drop zone or input field in the browser. 

We use [ProtoBuf.js](https://github.com/dcodeIO/ProtoBuf.js) which claims it is "Browser compatible".

Our [crc32c library](https://github.com/Voxer/sse4_crc32) is built from source but has a software fallback... I'm not sure what that means if that means there's a JS fallback.

[configstore](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/package.json#L53) won't work but we could save to browser LocalStorage.

Not sure on the compatibility of streams in the browser but I have good reason to believe it should work.

I'm assuming all requests to the API aren't restricted by cross-site protection i.e. they can make an XHR from a gcloud.js file hosted at theirsite.com to googleapis.com and it will work.

**Comment by callmehiphop** [comment]
Might be worth mentioning that with browserify you can [specify browser-specific overrides](https://github.com/substack/node-browserify#user-content-browser-field) pretty easily.

**Comment by JustinBeckwith** [comment]
Closing this in favor of #2936 2933
