### ISSUE TITLE
@google-cloud/secret-manager SecretManagerServiceClient.secretVersionPath throws a type error

### ISSUE THREAD

**Issue by dicearr** [googleapis/google-cloud-node#5319]
#### Environment details

  - which product (packages/*): **@google-cloud/secret-manager@5.5.0**
  - OS: **Darwin 21.6.0 Darwin Kernel Version 21.6.0**
  - Node.js version: **v19.6.1**
  - npm version: **9.4.0**
  - google-cloud-node version:

#### Steps to reproduce

```tsx
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';

const secretManager = new SecretManagerServiceClient();

secretManager.secretVersionPath('the-project-id', 'the-secret-name', 'latest'); // Throws
```

The provided code snippet throws the following error:

```
/path/to/project/node_modules/@google-cloud/secret-manager/build/src/v1/secret_manager_service_client.js:1161
        return this.pathTemplates.secretVersionPathTemplate.render({
                                                            ^
TypeError: Cannot read properties of undefined (reading 'render')
    at SecretManagerServiceClient.secretVersionPath (/path/to/project/node_modules/@google-cloud/secret-manager/build/src/v1/secret_manager_service_client.js:1161:61)
    ...
```

Seems to me that this pull-request (https://github.com/googleapis/google-cloud-node/commit/5e145530c217cc87ee2d2e9f6124c5091534fc5e) could've broken the `secretVersionPath` method, as there is no `secretVersionPathTemplate` in the `pathTemplates`.

**Comment by jacopofranza** [comment]
same problem here

**Comment by DanielLoyAugmedix** [comment]
Same issue for my team. This is a blocker.

**Comment by Red-Pandaz** [comment]
I just encountered this problem. Was able to get around it by using 5.3.0 instead. I'll get the latest version once this is fixed.
