### ISSUE TITLE
I want to use GOOGLE_APPLICATION_CREDENTIALS json file

### ISSUE THREAD

**Issue by okumar-SDG** [googleapis/google-cloud-node#5568]
Hi team,
instead of using export GOOGLE_APPLICATION_CREDENTIALS="/home/ec2-user/Projects/credentials.json"

I want something like const  GOOGLE_APPLICATION_CREDENTIALS="/home/ec2-user/Projects/credentials.json" in this code , can anyone help

`// Imports the Google Analytics Data API client library.
const {BetaAnalyticsDataClient} = require('@google-analytics/data');

// Using a default constructor instructs the client to use the credentials
// specified in GOOGLE_APPLICATION_CREDENTIALS environment variable.
const analyticsDataClient = new BetaAnalyticsDataClient();

// Runs a simple report.
async function runReport() {
  const [response] = await analyticsDataClient.runReport({
    property: `properties/${propertyId}`,
    dateRanges: [
      {
        startDate: '2020-03-31',
        endDate: 'today',
      },
    ],
    dimensions: [
      {
        name: 'city',
      },
    ],
    metrics: [
      {
        name: 'activeUsers',
      },
    ],
  });

  console.log('Report result:');
  response.rows.forEach(row => {
    console.log(row.dimensionValues[0], row.metricValues[0]);
  });
}
`

**Comment by sofisl** [comment]
@okumar-SDG, you can add a `keyfile` property to the constructor:

```
const analyticsDataClient = new BetaAnalyticsDataClient({keyfileName: 'path-to-your-keyfile'});
```

 see: https://github.com/googleapis/google-auth-library-nodejs/blob/0b78d91534d97b37859a2303b332f8ccd52dbf69/src/auth/googleauth.ts#L91-L99
