### ISSUE TITLE
Enterprise Knowledge Graph

### ISSUE THREAD

**Issue by Jimflip** [googleapis/google-cloud-node#5730]
### A screenshot that you have tested with "Try this API".

Yeah it's not in the client

### What would you like to see in the library?

Support for this would be great.

### Describe alternatives you've considered

simple fetch request, but documentation is very confusing to set up auth and it doesn't support API Keys.

**Comment by sofisl** [comment]
API keys are [accepted](https://github.com/googleapis/google-auth-library-nodejs). Please refer to our [authentication guide](https://github.com/googleapis/google-auth-library-nodejs) for more information. If you have another question, please open a new issue with a specific context + question related to the library. Thank you!
