### ISSUE TITLE
We either have a flaky or genuinely breaking samples test

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-cloud-node#5752]
Samples test is failing trying to grab the correct image: https://github.com/googleapis/google-cloud-node/pull/5751/checks?check_run_id=31518140342

cc @danielbankhead on rotation, PTAL

**Comment by danielbankhead** [comment]
Looks like a strange perms issue retrieving the kaniko image

**Comment by sofisl** [comment]
Seems like this is still happening... https://github.com/googleapis/google-cloud-node/pull/5754/checks?check_run_id=31697454507

**Comment by danielbankhead** [comment]
Not related to the infra outage?

**Comment by sofisl** [comment]
Woops! well let's close it until we've passed it and can know for sure.

**Comment by danielbankhead** [comment]
Looks like there's a `412` for the container registry deprecation (terrible design to throw a `412` for a warning):

`unexpected status code 412 Precondition Failed: Container Registry is deprecated and shutting down, please use the auto migration tool to migrate to Artifact Registry`

This is blocking releases, will investigate shortly.

**Comment by sofisl** [comment]
Solved this by actually migrating us to artifact registry following [these steps](https://cloud.google.com/artifact-registry/docs/transition/auto-migrate-gcr-ar#migrate-gcrio-hosted-ar). Follow up cl/690767506
