### ISSUE TITLE
Conversational Search: Add support for grounding

### ISSUE THREAD

**Issue by dtrenz** [googleapis/google-cloud-node#5768]
### A screenshot that you have tested with "Try this API".

Already supported in REST API: https://cloud.google.com/generative-ai-app-builder/docs/answer#return-support-scores

![Screenshot 2024-10-25 at 5 45 31 PM](https://github.com/user-attachments/assets/d91b25ec-d73c-4c7a-bc50-55403fa1c8f1)

### What would you like to see in the library?

I would like to see support added for `groundingSpec` in `answerQuery()` request and `groundingScore` in response.

**Comment by sofisl** [comment]
Hi @dtrenz, thank you for the feature request! Unfortunately this would be better placed in the API tracker itself, since this just means that unfortunately the API hasn't made this feature available in grpc yet. Thank you!
