### ISSUE TITLE
Text-to-speech 5.6.0 not on NPM

### ISSUE THREAD

**Issue by jacobpedd** [googleapis/google-cloud-node#5788]
Looking forward to using the new multi-speaker features in the new text-to-speech release. The changelog has been updated but the new version isn't available in NPM. Here's the changelog: https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-texttospeech/CHANGELOG.md

It's been about a week and I just want to make sure it wasn't forgotten :)

**Comment by sofisl** [comment]
Ack, we've been migrating our release process and there's some kinks. Working on it currently!

**Comment by sofisl** [comment]
Done! https://www.npmjs.com/package/@google-cloud/text-to-speech
