### ISSUE TITLE
Your `.github/scripts/close-invalid-link.cjs` is broken

### ISSUE THREAD

**Issue by jefer94** [googleapis/google-cloud-node#5826]
### Please make sure you have searched for information in the following guides.

- [X] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
- [X] Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
- [X] Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq
- [X] Check our libraries HOW-TO: https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md
- [X] Check out our authentication guide: https://github.com/googleapis/google-auth-library-nodejs
- [X] Check out handwritten samples for many of our APIs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples

### Documentation Request

Document this error properly https://github.com/googleapis/google-cloud-node/issues/5824

> `A link to a public Github Repository or gist with a minimal reproduction.`

I have:

1. A public link
2. A gist
3. A minimal reproduction

What do you want?, a frontend to run the SSML having a frontend written by us?

**Comment by jefer94** [comment]
![image](https://github.com/user-attachments/assets/8514dd63-9429-41ac-818e-e70aac19f954)

I ran this validation
- https://github.com/googleapis/google-cloud-node/blob/main/.github/workflows/issues-no-repro.yaml
- https://github.com/googleapis/google-cloud-node/blob/main/.github/scripts/close-invalid-link.cjs

It seems like whoever wrote this code thought, I am getting the markdown, and forever the line that will contain the URL is the 18, it's so wrong, that could be acceptable but if for any reason you have a bug in your code you will close that issue too, you aren't checking the error, and if you fail, you close an issue, and someone accepted that PR

You have to know that you must read line by line until read the title, and then make something like `x === ""` or `x.startswith('http')`

Clarifying this point, could someone reopen, or whatever, opens the issue

**Comment by sofisl** [comment]
You're completely right about this. It's an edge case and I've had trouble figuring out the best way to validate this line. Unfortunately it's not supported by current [yaml](https://github.com/orgs/community/discussions/4629). Perhaps the best way forward is just to move it up so that we always have it in a standard place (for now).

**Comment by jefer94** [comment]
I don't understand your assertion:

1. The YML seems like a Node env, it received `issue.data.body`, it has a `split`, and it seems like a `string`, what's my point, Javascript support iterate an array, when you reach the same line could work, besides, you have known the next title and you could use a `break` when you see it in a conditional
2. If you would want to hardcode the line of the URL, it must be the first section, so, nobody could change the line number
3. Even if I tried to resubmit this issue, it wouldn't work because I'm providing two screenshots, I could re-submit the issue by leaving the image in another section, but:
  - It's inaccurate 
  - It enforces ignore issues and nobody is checking them
  - You could think this is the responsibility of whoever opened the issue, actually, this is a paid service, and Google must provide good services to their customers, I had a least 20% failure and I had to switch to another solution, so, you have to understand the importance of this issue, Google potentially keeps losing a client due to this policy, I thought in remove the support to Google Text to Speech in favor of another, what am I trying to say you? this is an issue with a big importance

**Comment by jefer94** [comment]
Same issue:
- https://github.com/googleapis/google-api-nodejs-client/issues/3591
- https://github.com/googleapis/google-api-nodejs-client/blob/main/.github/scripts/close-invalid-link.cjs
- https://issuetracker.google.com/issues/380295064

Hey, the policy to report issues in Google is so disgusting, it's mentally exhausting, a Google Team must be able to send reports to another Google Team, I mean, I am not a Google worker, I am forced to deal with it

What I reported?, just see
![image](https://github.com/user-attachments/assets/02060655-2e59-4a52-ab99-dfbfce84f0fd)

I am frustrated, I want to never send any issues again

**Comment by sofisl** [comment]
Hi @jefer94, as I have already described to you earlier and in #5833, you are right and I need to fix this - I haven't had time to do it this week. I have already marked this issue as a p1 and acknowledged it. However, I will be closing this one and opening another one in its stead because you are violating our [code of conduct](https://github.com/googleapis/google-cloud-node/blob/2e5850959c721371fbcd61dc71da359ccdd4722b/CODE_OF_CONDUCT.md). You are right there is an issue and I will fix it - please remember there are humans behind this issue queue and we are doing our best :)

**Comment by jefer94** [comment]
@sofisl I am not saying that I'm frustrated about you. I'm frustrated about Google Policy, I wrote about that issue because it is related to this issue

Addressing that I am "violating our code of conduct," I will split the mistake by each one because it seems like you are telling me that I did something related to hating someone or laughing about newbies

About @sofisl 

- the only thing that you must do is work the stipulated work hours, I’m not saying you have to work twice to resolve our issues

About Google

- Google must keep the quality of its products, and respect its customers and beta testers
- Google is responsible to be fear of they customer and the beta testers
- Google is responsible for contract more developers if needed
- Google is responsible for its policy and bureaucracy 

About me

- As you @sofisl I'm working, if someone doesn't work I must leave a constancy of it
- Maybe if I explained what happened wrong, but the error was not only a logic error, it's too don't have empathy, then I said `that could be acceptable` I didn't put so much importance in it, but `and someone accepted that PR` I'm making a strong point in that quality assurance fails

Right now clarifying those points, @sofisl , do you think that is fear everything I had to go through? Nothing starts or ends in you, who is in charge of maintaining and enforcing the respect towards the client and beta tester? We are human beings too and we have been going through a nightmare because Google has been systematically disrespecting us

I will leave all that happened to me, for everyone to judge if this is fair and maybe add a clause to our code of conduct about Google respecting our, because we are human beings

https://github.com/googleapis/google-cloud-node/issues/5822#issuecomment-2484494317
https://github.com/googleapis/google-cloud-node/issues/5823#issuecomment-2484505344
https://github.com/googleapis/google-cloud-node/issues/5824#event-15342470199
https://github.com/googleapis/google-cloud-node/issues/5833#event-15377330425
https://issuetracker.google.com/issues/378688996
https://issuetracker.google.com/issues/380282494
https://issuetracker.google.com/issues/380295064
https://github.com/googleapis/google-cloud-python/issues/13194#event-14829117978
https://github.com/googleapis/google-cloud-python/issues/13102#issuecomment-2477153322
https://github.com/googleapis/google-api-nodejs-client/issues/3591#event-15401773702

I suppose that it's fair
